job-server/src/spark.jobserver/JobServerNamedRdds.scala, job-server/test/spark.jobserver/NamedRddsSpec.scala
The code was trying to override the StorageLevel on the given RDD, but some rdds are cached by spark (ie: the ones in a MatrixFactorization result of ALS.train)
=> Support storing rdds that have a storeLevel already set

bin/server_start.sh, job-server/config/local.sh.template
In Spark we normally use SPARK_CONF_DIR to represent Spark's config directory. Maybe changing the name here is better.
=> SPARK_CONF_HOME to SPARK_CONF_DIR

README.md, job-server/src/spark.jobserver/WebApi.scala
"mem-per-node" is not valid, because in the config, using "memory-per-node". For example, using  "memory-per-node" in SparkJobUtils.scala, not "mem-per-node".
=> Change "mem-per-node" to "memory-per-node"

README.md, job-server/config/local.conf.template, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JobManagerActor.scala
When creating context, I want to add uris of dependent jars. And i want to add different jars for different context. If option "dependent-jar-uris" is a list, there is impossible to using "POST /contexts/?dependent-jar-uris=[file:///some/path/of/my-foo-lib.jar]" to create context. So i change the type of "dependent-jar-uris".
For example:
curl -d "" 'localhost:8090/contexts/test-context?dependent-jar-uris=file:///some/path/of/my-foo-lib.jar,file:///some/path/of/my-boo-lib.jar'
In this way, when creating test-context, i pass the dependence jars for this context.
See: https://github.com/spark-jobserver/spark-jobserver/pull/65
=> uris of jars is a string list, or a string separated by commas ','

README.md
I spent at least an hour pulling out my hair when my NamedRdds would disappear at the last moment. Turns out there's a big difference between ad-hoc queries and a pre-configured context when your queries are related to each other.
This documentation change aims to clarify that difference with the fewest possible changes to the README.
=> Clarify ad-hoc vs permanent context modes in README

akka-app/src/ooyala.common.akka/web/JsonUtils.scala, akka-app/test/ooyala.common.akka/web/JsonUtilsSpec.scala
Use a pattern guard to filter cases where a map is empty. Empty maps
cause an exception without the guard in place.
This patch was inspired by 434337e in the ooyala master branch.
=> fix: Serialize empty maps.

bin/server_start.sh, bin/server_stop.sh
when running server_start.sh, the $PIDFILE should be created in the path of $appdir. For example, running $appdir/server_start.sh in the current directory (eg,  /home), the PIDFILE  should not created in the path of  /home/. Because there is a issue to find PIDFILE  when running  server_stop.sh.
=> server_start.sh and server_stop.sh should running in any path

job-server/src/spark.jobserver/JobManagerActor.scala
Previously it was intended to use "SparkContext's ActorSystem threadpool for the futures, so we don't corrupt our own"; however the assignment
implicit val executionContext = sparkEnv.actorSystem
does not serve said purpose. It is removed.
=> Removed confused assignment of execution context.

README.md
The current distribution at Bintray (https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/) is partitioned by Scala version, which requires %% instead of % when specifying the library dependency in sbt. Using % causes resolution errors.
=> Update libraryDependencies instructions to use %%

bin/server_start.sh
This fixes logging in the using spark-submit instead of class, see #164
=> make logs in spark-submit write to specified log4j config

README.md, bin/server_start.sh, doc/troubleshooting.md, job-server/src/spark.jobserver/JobServer.scala, job-server/src/spark.jobserver/WebApi.scala
The hope is that this will solve a bunch of classpath issues that different folks have been seeing, since job server will launch as a regular Spark application.
You can try this branch out, but note that logging just goes to stdout right now.  I haven't figured out how to make Spark use our own log4j config, short of copying our log4j.properties into the `$SPARK_HOME/conf` dir.
Also, @Ankit1010 have a look at this.   Two thoughts:
1. Using `spark-submit` would be perfect for launching the forked context JVM.   In fact, we may be able to use SparkSubmitDriverBootstrapper.scala, which is part of Spark and means we don't even need to deal with process forking ourselves.
2. Outside of the JobManager, the job server doesn't really need to interact with Spark.  Perhaps the main job server (web …
=> Use spark-submit instead of compute-classpath.sh

doc/contexts.md, job-server-extras/src/spark.jobserver/context/StreamingContextFactory.scala, job-server-extras/test/spark.jobserver/StreamingJobSpec.scala, job-server/src/main/resources/application.conf, job-server/test/spark.jobserver/JobSpecBase.scala
This Thread.sleep should be replaced with some proper status message whenever we have that feature.
Something that would indicate that a streaming batch has been processed
=> Make Streaming Context more configurable & Fix Tests

job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/LocalContextSupervisorActor.scala
When submit a job, if sparkcontext not alive (e.g. yarn application -kill $appId), the context meta is still exist in jobserver. So when I want to recreate a context, the jobserver tell me the context is existed.
So I make this PR, When submit a job, if sparkcontext not alive, send ContextStopped message to LocalContextSupervisorActor to do the sc clean up job.
=> When submit a job, if sparkcontext not alive, send ContextStopped message to LocalContextSupervisorActor to do the sc clean up job.

job-server/src/spark.jobserver/util/SparkJobUtils.scala, job-server/src/spark.jobserver/util/SparkMasterProvider.scala, job-server/test/spark.jobserver/util/SparkMasterProviderSpec.scala
Currently the spark.master address passed into the JobServer is used for
all Contexts launched in the future. If the Spark master changes due to
HA Systems the JobServer can no longer make new Contexts. This patch
adds a hook to a new class via spark.master.provider. With this a user
can implement a custom SparkMasterProvider object which will be invoked
on the creation of new SparkConfs. This allows for a dynamic adjustment
of the spark.master property for newley created contexts.
=> Adds Hook For Custom SparkMasterProvider

bin/kill-process-tree.sh, bin/server_package.sh, bin/server_stop.sh
This is shamelessly copied from https://github.com/riptano/spark-jobserver and all credit goes to @RussellSpitzer 
It fixes `server_stop.sh` to properly kill `spark-submit` jobs
=> fix server_stop for spark-submit start-start

bin/server_deploy.sh
The server_deploy.sh script didn't copy up the kill-process-tree.sh script so server_stop.sh failed.
=> Add kill-process-tree.sh to server_deploy.sh

project/Dependencies.scala
Spray Json was upgraded to 1.3.2.
Changelog of 1.3.2: https://github.com/spray/spray-json/blob/master/CHANGELOG
=> Upgrade to spray-json 1.3.2

job-server/config/log4j-server.properties
DatePattern is no parameter of the RollingFileAppender and creates a warning when starting the Job-Server
log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
http://www.tutorialspoint.com/log4j/log4j_logging_files.htm
=> Remove wrong DatePattern Parameter

bin/server_start.sh, job-server/config/local.sh.template
If you change the YARN_CONF_DIR in your env.sh files the parameter was not used by the spark-submit shell because the server_start.sh did not export the parameters.
Effect: The YARN_CONF_DIR of the settings.sh has no effect. The jobserver will always try to connect to localhost(default) in yarn client mode.
=> Bugfix: Custom YARN_CONF_DIR remain unused

project/Dependencies.scala
Attempting to run a job that uses the AWS client raised this exception
```
java.lang.IllegalStateException: Joda-time 2.2 or later version is required, but found version: null
at com.amazonaws.util.DateUtils.handleException(DateUtils.java:147)
at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:195)
at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:78)
...
```
Updating the dependency to Joda Time 2.2 avoids the exception and does not break any unit tests.
Compatibility notes from http://www.joda.org/joda-time/upgradeto220.html
```
Compatibility with 2.1
----------------------
Build system - No
- Ant build removed. Build only on Maven now.
Binary compatible - Yes
Source compatible - Yes
Serialization compatible - Yes
Data compatible - Yes, …
```
=> Update Joda Time dependency to version 2.2

job-server-extras/src/spark.jobserver/SparkStreamingJob.scala, job-server-extras/src/spark.jobserver/StreamingTestJob.scala, job-server-extras/src/spark.jobserver/context/StreamingContextFactory.scala
This would break the code of anyone using SparkStramingJob... so should we break that or I can add another trait called SparkStramingJob that extends SparkStreamingJob, and mark it as deprecated and we can delete that one on another release.
=> Fix typo in SparkStreamingJob

README.md, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JarManager.scala, job-server/src/spark.jobserver/JobServer.scala
This PR allows the user to supply a `spark.jobserver.job-jar-uris` configuration object that will cause SJS to store jars at the given URIs for the given application names. It behaves as if the first thing you do when SJS starts is post jars to the `localhost:8090/jars/appName` endpoint with a set of local jars.
The idea comes from @hectcastro.
=> Store initial job jars on startup.

job-server-extras/test/spark.jobserver/StreamingJobSpec.scala, job-server/src/spark.jobserver/JobInfoActor.scala, job-server/src/spark.jobserver/io/JobDAO.scala, job-server/src/spark.jobserver/io/JobFileDAO.scala, job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/test/spark.jobserver/InMemoryDAO.scala, job-server/test/spark.jobserver/io/JobSqlDAOSpec.scala
Earlier we were fetching all DB records into memory and then running limit query in memory. For a bigger production system this is causing issues as the records grow beyond certain number. This patch does  the following
1. Modifies the signature of getJobInfos() to take limit parameter so that we always fetch certain number of records from DB.
2. Add new API getJobInfo() to retrieve a information about a specific Job Id. Earlier we were performing a lookup in memory.
3. Adjust tests accordingly.
=> Fix issue #229: Always use limit while reading from DB

job-server/src/spark.jobserver/context/SparkContextFactory.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala
There was a fallback in SparkContextFactory that made the default config override job config instead of the other way around.
Since LocalContextSupervisorActor and WebApi do the fallback action there's no need to do it again in the context factory.
=> Remove unnecesary fallback in SparkContextFactory 

job-server/src/spark.jobserver/io/JobSqlDAO.scala
This was actually done for debugging. This could pollute the log.
=> Remove unnecessary logging of SQL query

job-server-api/src/spark.jobserver/JavaSparkJob.scala, job-server-tests/src/main/java/spark.jobserver/JavaHelloWorldJob.java
Add a JavaSparkJob class to make it easy for Java folks to write jobs for SJS, with a JavaHelloWorldJob example.
Missing:
* Adding java collections to the list of types serialized into JSON.
=> JavaSparkJob

job-server/src/spark.jobserver/io/JobSqlDAO.scala
Else we get string limit errors in runtime.
=> In Postgres, you need to explicitly map string to varchar. 

job-server/src/spark.jobserver/JobInfoActor.scala, job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala, job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala
As of now /jobs/jobId returns status and result which is very minimal.
Since we lack an API which returns more information like the /jobs API
returns as a list, amend /jobs/jobId to return extra information.
This commit makes job status uniform across /jobs and /jobs/jobId. We no
longer have "OK" status instead it will be the same as "FINISHED"
Now GET /jobs/jobId takes different route instead of the current one.
User => WebAPI => GetJobStatus => WebAPI => GetJobResult => WebAPI => User
And DELETE /jobs/jobId takes
User => WebAPI => GetJobStatus => WebAPI => User
=> Cleanup /jobs/jobId APIs

README.md, project/Dependencies.scala, project/plugins.sbt
The latter due to another user discovered dependency issue.
This should help resolve the spark-streaming dependency issue and help the builds pass.
=> Upgrade to Spark 1.5.1 and sbt-scoverage 1.2.0

job-server/src/spark.jobserver/JobInfoActor.scala, job-server/src/spark.jobserver/WebApi.scala
After PR-270 DELETE API for following scenarios stopped working.
DELETE /jobs/non-existing-job-id
DELETE /jobs/finished-job-id stopped working.
=> Fix regression caused by PR-270

job-server/src/spark.jobserver/JobInfoActor.scala, job-server/src/spark.jobserver/WebApi.scala
After PR-270 DELETE API for following scenarios stopped working.
DELETE /jobs/non-existing-job-id
DELETE /jobs/finished-job-id stopped working.
=> Back-port Fix regression caused by PR-270 from master

job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala, job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala
When I try to post a big jar in spark-jobserver, I am getting the error response:
```
{
"status": "ERROR",
"result": {
"message": "Ask timed out on [Actor[akka://JobServer/user/jar-manager#735054989]] after [3000 ms]",
"errorClass": "akka.pattern.AskTimeoutException",
"stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)", "scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", …
```
=> Small ask timeout bug

project/Build.scala, project/Dependencies.scala
This changes the base docker image from ottoops/mesos-java7 to java:7-jre, this alone reduces the image size by about half, ~785MB from ~1.54GB.
If there is a strong preference towards the OracleJDK, we can merge in the [oracle-java7-installer](https://github.com/OttoOps/docker-containers/blob/master/mesos-java7/Dockerfile#L6).
The Mesos library is now installed from apt and configurable via the MESOS_VERSION environment variable.
The docker tag now contains the version for Mesos and Spark, example: 0.6.1-SNAPSHOT.mesos-0.25.0.spark-1.5.1. This should let users discern the correct tag to pull based on their environment.
=> Docker image improvements and parameterized Mesos version.

bin/manager_start.sh, bin/server_start.sh, job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala
We have deployed the feature/context-per-jvm , but found some problem:
* manager_start.sh and server_start.sh start use $appdir without initial
* AkkaClusterSupervisorActor blocked when creating new persist context at process.waitFor api by unread inputstream and outputstream from sub process stdin/stdout/stderr to the main process, so the main thread block and no result return to the POST /context/name request, cause timeout. So I try to add some processIO handler to consume stdin/stderr stream and also redirect manager_start.sh command to /dev/null, I am not quite sure about which really fix the block problem, but finally it works, and scala process api looks better than the native java api.
We have test deploy/create context/run job with the context, all works but restart job-server …
=> Fix shell problem, change processbuilder to scala style api

README.md, project/Dependencies.scala
Spark 1.5.2 was released on Nov 9 https://github.com/apache/spark/releases/tag/v1.5.2
=> Update spark version to 1.5.2

doc/yarn.md
As discussed in the mailing list, the start-server.sh does not contain the '--master yarn-client' option because it is not used in all kinds of deployments. The yarn docs don't say anything about it. I just added few lines into the relevant doc page.
=> Update yarn related docs.

job-server/src/spark.jobserver/auth/SJSAuthenticator.scala
Fixes a bug that causes java.util.NoSuchElementException: None.get error when operation attempted with auth enabled and no user name / password supplied. This bug in turn seemed to stop the UI working the auth enabled.
I'm not much of a scala expert so there may be a better way to do it but this worked in all my testing.
=> Fix bug - invalid error w no user/pass

job-server/src/spark.jobserver/util/SparkMasterProvider.scala, job-server/test/spark.jobserver/util/SparkMasterProviderSpec.scala
Currently spark master provider configuration property is
spark.master.provider, which is colliding with spark.master which is
used for spark master URL.
=> Fix config collision in spark master provider

project/Dependencies.scala
Spark-1.6.0 uses Scala 2.10.5
https://github.com/apache/spark/blob/branch-1.6/pom.xml#L166
Dependencies should be in sync with Spark
=> Update Dependencies to use scala-library 2.10.5

doc/EMR.md
Spark-1.6.0 uses Scala 2.10.5
https://github.com/apache/spark/blob/branch-1.6/pom.xml#L166
SJS on EMR should be in sync with Spark
=> Update EMR.md to use SCALA_VERSION 2.10.5

bin/server_start.sh
Currently server_start.sh hang at the end if run it inside another script via ssh
if we run cmd on background we need to redirect /dev/null to stdin
Redirecting /dev/null to stdin will give an immediate EOF to any read call from that process. This is typically useful to detach a process from a tty (such a process is called a daemon). For example, when starting a background process remotely over ssh, you must redirect stdin to prevent the process waiting for local input.
Another reason to redirect to /dev/null is to prevent an unused file descriptor being created for stdin. This can minimize the total open file handles when you have many long running processes.
=> Redirect /dev/null to stdin in server_start.sh

doc/troubleshooting.md, job-server/config/local.conf.template, job-server/src/main/resources/application.conf, job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala
See #147 for more details.  Basically this allows larger job results to be returned by default.  It is a short term solution;  the longer term solution would be to chunk and pre-serialize the result.   pre-serializing might be a good solution for storing results in a database anyhow.
=> Allow larger job results to be returned by default

bin/setenv.sh
This allows for `DEBUG_PORT` to be set as env var, when set, this turns on remote debugging for SJS
=> add in an option to debug

job-server-extras/src/spark.jobserver/NamedObjectsTestJob.scala, job-server-extras/test/spark.jobserver/NamedObjectsJobSpec.scala, job-server-extras/test/spark.jobserver/NamedObjectsSpec.scala, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/JobServerNamedObjects.scala, job-server/test/spark.jobserver/JobWithNamedRddsSpec.scala, job-server/test/spark.jobserver/LocalContextSupervisorSpec.scala, job-server/test/spark.jobserver/NamedObjectsRDDsOnlySpec.scala
Fixes problem that references to named objects were lost inbetween jobs.
Sorry about the delay infixing this !
=> NamedObjects: cache with references to named objects must be a singleton

bin/manager_start.sh, bin/server_start.sh, bin/setenv.sh, job-server/config/local.sh.template
With newer versions of Netty, it appears `MaxDirectMemorySize` needs to be
increased for certain uses cases
This change exposes an env var, `MAX_DIRECT_MEMORY`, which allows for setting
this value
=> expose MaxDirectMemorySize via env var

README.md, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/context/SparkContextFactory.scala, job-server/src/spark.jobserver/util/SparkJobUtils.scala, job-server/test/spark.jobserver/LocalContextSupervisorSpec.scala
I wanted to be able to add things to the Spark Hadoop configuration, specifically things like the shuffle manager and ParquetOutputCommitter which require you to set them via the hadoop configuration.
I added the ability to be able to add to the spark context's hadoop configuration. I think I may have to add this to the extras-api stuff too.
=> Added ability to add to Spark's Hadoop configuration

README.md, job-server/config/local.conf.template, job-server/src/spark.jobserver/ChunkEncodedStreamingSupport.scala, job-server/src/spark.jobserver/ChunkEncodingActor.scala, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala
If a job result is scala Stream[Byte] it is returned in body using chunk encoding
=> Added support for chunked encoding when job result is a Stream[Byte]

job-server-api/src/spark.jobserver/NamedObjectSupport.scala
See #456  
The change was simple. Just exchange for the supertype of SparkJob and SparkSqlJob which is SparkJobBase.
I tested it locally and it seems to work.
=> self-reference is now of supertype SparkJobBase

job-server/src/main/resources/application.conf
=> Fix manager_start not found during docker deployment

job-server/src/main/resources/application.conf
This reverts commit 33735ad1a810985b82c65eae3de3f27b77bdb607.
=> Revert "Fix manager_start not found during docker deployment"

README.md, job-server-extras/test/spark.jobserver/NamedObjectsJobSpec.scala, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala, job-server/src/spark.jobserver/WebApi.scala, job-server/src/spark.jobserver/auth/AuthInfo.scala, job-server/src/spark.jobserver/util/SparkJobUtils.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/auth/SJSAuthenticatorSpec.scala, job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala
Added option to require that proxy users must be identical to the authenticated user.
In order to support secured clusters it is necessary to ensure that the user running a spark context is identical to the authenticated user. We added a boolean configuration option (`shiro.use-as-proxy-user`). When authentication and this flag are activated, then spark.proxy.user is always set to the name of the authenticated user. Users will ever only see and be able to manipulate their own contexts. An internal prefix is used to ensure that no naming conflicts arise when different users use the same name for their respective contexts.
Note that in this case the `spark.proxy.user` parameter in the following call is always ignored!
POST /contexts/my-new-context?spark.proxy.user=<IGNORED>
=> Per-user authenticated contexts

job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/src/test/resources/local.test.jobsqldao_dbcp.conf, job-server/test/spark.jobserver/io/JobSqlDAOSpec.scala
Allow user to enable/disable DBCP. By default it is not required as it
is only useful when there is huge number of database connections
involved. Also in some scenarios like when pgpool is running in front of
PostgreSQL DBCP is creating issues. There is no need for client side
pool in such cases.
=> Make dbcp optional

project/Build.scala
It looks like without file protocol override does not happen.
=> Fix for issue #475

README.md, job-server-extras/src/spark.jobserver/NamedObjectsTestJob.scala, job-server-extras/test/spark.jobserver/HiveJobSpec.scala, job-server-extras/test/spark.jobserver/NamedObjectsJobSpec.scala, job-server-extras/test/spark.jobserver/NamedObjectsSpec.scala, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/auth/SJSAuthenticator.scala, job-server/test/spark.jobserver/JobManagerActorSpec.scala, job-server/test/spark.jobserver/JobSpecBase.scala, job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala
Fixes for flaky tests reported by @hntd187 and others. 
1. Timeout test in WebApiWithAuthenticationSpec uses a TimeoutException to ensure that an Exception is always thrown.
2.  NamedObjectsSpec only creates its SparkContext when run and only once.
3. NamedObjectsTestJob sleeps 1 ms so that other threads can do their work and release the job resources.
4. HiveContextFactory in HiveJobSpec needs to stop the SparkContext if it fails to create the Hive context. We might want to add this check to 'spark.jobserver.HiveContextFactory' as well, just in case.
5. JobSpecBaseBase.afterAll uses TestKit.shutdownActorSystem(system) instead of the ooyala version. It also only shuts down the manager in afterAll (as opposed to after each method).
=> flaky-tests:

README.md, job-server-extras/test/spark.jobserver/StreamingJobSpec.scala, job-server/src/spark.jobserver/CommonMessages.scala, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/JobStatusActor.scala, job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/JobManagerSpec.scala, job-server/test/spark.jobserver/JobStatusActorSpec.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala
POST /jobs/ should return as many information as GET /jobs/<jobId>
Also the returned json should not have a result key in the json to make
it consistent.
=> Make create job API to return more information

bin/ec2_deploy.sh
Fix broken ec2 scripts links. EC2 scripts are moved out of spark
repository to amplab/spark-ec2 as part of SPARK-12735.
=> Fix for issue #369

project/Build.scala
Make `job-server-extras/assembly` package job-server classes too
Issue reported by @bjoernlohrmann on gitter channel
=> Revert regression caused by e57bc0ab8bd4b40d3b986841a0349e59c7a15f39

project/Build.scala
Re: #517 - Add Scala version to docker tag in order to build images for Scala 2.10 and Scala 2.11.
=> Add Scala version to docker tag

bin/setenv.sh
This fixes a regression that was fixed in #136 and #137, without this, it breaks if you aren't setting `SPARK_EXECUTOR_URI`
=> Only set spark.executor.uri if env var is set

README.md
In the README file, it was written that "...it would require serialising Stream[_] blob between processes. For now use Stream[_] job results..." yet, the underscore is a Markdown indicator, used to convey emphasis; the end result was that "] blob between processes. For now use Stream[" was written in italics, and the underscores were hidden. Fixed (escaped).
=> Added escape to README

job-server/config/docker.conf, project/Build.scala, project/Dependencies.scala, project/plugins.sbt
This allows to compile for Scala 2.11. To build for Scala 2.11, run `SCALA_VERSION="2.11.8 sbt docker`.
I've already built 0.6.2 images for both Scala versions using this build file:
https://hub.docker.com/r/mariussoutier/spark-jobserver/tags/
The 0.7.0 snapshot has an Akka issue inside Docker which I'm still investigating, but it doesn't seem related to building from source.
=> Build Spark from source in Docker image

job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala
I have a lot of spark configs I want to set on my spark context. The only way to do this when creating a context is to supply the configs as URL parameters, but I get a `414: URI Too Long` because there are too many.
Add support for typesafe config in the payload of the `POST /contexts/<contextName>` endpoint. This is the same support for the `POST /jobs` endpoint - the user can supply:
```
spark.context-settings {
hadoop {
}
}
=> POST /contexts/<contextName> takes typesafe config payload

README.md, job-server/src/spark.jobserver/routes/DataRoutes.scala, job-server/test/spark.jobserver/WebApiSpec.scala
Currently data file delete api expects encoded URI. Enhance it to use
the path as such. This would help the user not to encode path.
Added examples
=> Fix for Issue #507: Fix DELETE /data/<filename> issue

README.md, project/Versions.scala
Updated Spark version to 1.6.2.
Since this is a minor update, it should be backward compatible. Since we've been using the 1.6.x branch for sometime, this should just fix bugs in Spark.
=> Updated Spark version

ci/install-python-dependencies.sh, job-server-python/src/python/sparkjobserver/subprocess.py
Debugging exceptions was very difficult without the exception stack trace. There was also a whitespace missing.
=> Include Python exception stacktrace on failure

job-server/src/main/resources/application.conf, job-server/src/main/resources/db/postgresql/migration/V0_7_0/V0_7_0__init_tables.sql, job-server/src/spark.jobserver/WebApi.scala, job-server/src/spark.jobserver/cassandra/Cassandra.scala, job-server/src/spark.jobserver/io/FileCasher.scala, job-server/src/spark.jobserver/io/JobCassandraDAO.scala, job-server/src/spark.jobserver/io/JobDAO.scala, job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/src/test/resources/local.test.jobsqldao.conf, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala, job-server/test/spark.jobserver/io/JobCassandraDAOSpec.scala, project/Build.scala, project/Dependencies.scala, project/Versions.scala
Support for cassandra datastorage backend. We discussed this with @velvia at gitter.
Implemented for cassandra 2.* 
Some details still need to be improved:
1. wontfix?: filter in cassandra, instead of application (by job status)
Schema: 
`
CREATE TABLE spark_jobserver.jobs (
job_id uuid PRIMARY KEY,
app_name text,
binary_type text,
classpath text,
context_name text,
end_time timestamp,
error text,
job_config text,
start_date date,
start_time timestamp,
upload_time timestamp
) 
CREATE TABLE spark_jobserver.jobs_chronological (
start_date date,
start_time timestamp,
job_id uuid,
app_name text,
binary_type text,
classpath text,
context_name text,
end_time timestamp,
error text,
job_config text,
upload_time timestamp,
PRIMARY KEY (start_date, start_time, job_id)
) 
CREATE TABLE …
=> cassandra support

job-server/src/main/resources/html/js/spark-jobserver-ui.js
We try to run the job-server behind reverse proxy with authentication as https://admin.example.org/spark-job-server/ but since the JSON is hardcoded to fetch root paths it will return 404. This change makes sure it requests the json relative to the root of the job-server directory
=> Use relative paths so it works if running in a context-path

job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala
Running jobserver with context-per-jvm results in remote jobmanager
actors, manually joining the jobserver cluster. After removing a
context, the actor stops and becomes unreachable within the cluster. We
have to manually remove the actor from the cluster (status down) before
the cluster accepts new clients again.
See http://doc.akka.io/docs/akka/2.3.15/scala/cluster-usage.html#Automatic_vs__Manual_Downing
=> Change cluster status of removed contexts to down (fixes #466).

job-server-extras/src/spark.jobserver/python/PythonContextFactory.scala
This is a fix for https://github.com/spark-jobserver/spark-jobserver/issues/572.
=> Add missing imports for Python contexts

job-server-extras/src/spark.jobserver/HiveTestJob.scala, job-server-extras/src/spark.jobserver/SparkHiveJob.scala
I wanted to use Hive jobs but it _looks_ like the only way to do that is by converting my jobs to the old, less type safe API. So I made this.
I would've converted SQL jobs also but I wasn't sure if there was a reason why SparkHiveJob used the older API.
=> Convert SparkHiveJob to use new API

bin/ec2_deploy.sh, job-server/config/user-ec2-settings.sh.template
- Fix a broken mkdir by adding -p option
- Get spark-ec2 from its new location as a separate project
- Add additional configuration
=> Make ec2_deploy.sh work with current spark-ec2

doc/troubleshooting.md, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/JobWithNamedRddsSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
We poll the REST API for job status/result and sometimes the json contains status finished but no result. 
This happens if the job manager send a status update (finished) but did not yet finished the results transfer.
This PR fix the send order within the job manager actor and improves the web api error handling.
=> Send result before finish event in job manager actor

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/util/StartJobSerializer.scala, job-server/src/test/resources/startjobSerializerConfig.conf, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/util/StartJobSerializerSpec.scala
Passing in 155K job config input string resulted in Akka timeout response to the job.
In WebApi, when creating JobManagerActor it fails to serialize jobConfig object when greater
than 64K (not verified). Change is to serialize the config object as a string and recreate
it when processing the job.
=> Change to increase job config input size

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
For both these routes, there was a race condition when you immediately
try and check the status of a job after starting or stopping it.
For example, if you POST'ed an async job and then immediately try and
do a GET on that jobId, the jobInfoActor may not have persisted the job
yet, so you would get a 404. Similiar could happen for stopping a job,
if you immediately tried to GET after cancelling, it may still show as
RUNNING
=> Eliminate POST and DEL /job race conditions

build.sbt, job-server-extras/src/main/scala/spark/jobserver/python/PythonJob.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonHiveContextFactorySpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonSQLContextFactorySpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonSparkContextFactorySpec.scala, job-server-python/src/python/build.cmd, job-server-python/src/python/run-tests.cmd, job-server-python/src/test/scala/spark/jobserver/python/SubprocessSpec.scala, job-server/src/test/scala/spark/jobserver/WindowsIgnore.scala, project/PythonTasks.scala
I'm one of those poor guys who mainly (has to) develop(s) on Windows. 
Tests for job-server-python and job-server-extras don't run without errors on Windows 7 (might be different for Windows 10 with Linux subsystem). So, I tried to fix the test-issues on Windows. With a very few exceptions (see below), I was successful. Would really ease my work if this got merged.
Thanks and best regards, Tim
* Adds Windows-scripts for Python tasks: build.cmd and run-tests.cmd
* Makes a minimal change to PythonJob to create OS-specific pythonPath-delimiters (Windows needs a semicolon instead of a colon)
* Introduces tag "WindowsIgnore" to mark (the very few) tests that do not run on Windows
* Tags PythonHiveContextFactorySpec tests as WindowsIgnore, because "delete Derby lock file"-workaround for …
=> Fixes test issues on Windows

run_tests.sh
This will allow python packages installed using "pip --user" option to be used
without any issues.
Also add some print statements for clarity.
=> Use absolute path for pep8 binary

.travis.yml
Now the tests are running inside the docker. But codecov is unable to detect CI system. 
So pass codecov environment variables to docker run.
=> Pass codecov.io env variables to docker

job-server/config/shiro.ini.ldap.template, job-server/src/main/scala/spark/jobserver/auth/LdapGroupRealm.scala, job-server/src/test/scala/spark/jobserver/auth/LdapGroupRealmSpec.scala
This PR adds more filter configurations e.g. if you don't use the member attribute in your LDAP (see shiro template for details).
=> Cleanup LDAP authentication and add filter config.

README.md
adds test execution instructions for Windows users (follow-up to PR #728).
Side note to @hntd187: Concerning integrating Windows into CI: it seems that Travis CI still does not support Windows. An option would be AppVeyor for the Windows build. Does that make sense? Can one integrate both Travis and AppVeyor at the same time in one project? If yes, I will work on AppVeyor set up.
=> Updated README.md (Contribution and Development section): test execution on Windows

job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala
(Updated description to hopefully avoid any further confusion about the goal of this PR):
(1) When calling **DELETE /binaries/<appName>**, WebApi sends a DeleteBinary request to BinaryManager actor which returns a Future. (On completion of the future, OK is returned to the calling HTTP client)
(2) BinaryManager thereby internally sends DeleteBinary(appName) to JobDAOActor
(3) JobDAOActor invokes deleteBinary on JobDAO trait and returns the result to BinaryManager 
=> The used implementation is JobSqlDAO
(4) JobSqlDAO's deleteBinary method looks like this:
```
override def deleteBinary(appName: String): Unit = {
deleteBinaryInfo(appName)
cleanCacheBinaries(appName)
}
```
**HERE IS THE IMPORTANT POINT:**
(5)	
```
private def deleteBinaryInfo(appName: String): Future[Int] = { …
```
=> Fixes #746: Random failure of deleteBinaries test case

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala
* #681 
* #761 
When no driver-mode is set, job-server will use default client mode and no error thrown
It is my mistake to use `Option` not `Try` to execute config.getString method, There is no default config for spark.jobserver.driver-mode So it will cause error.
Add a new line `driver-mode = client` to avoid this error, also change Option to Try if no default value is set to avoid throw an exception.
=> fix(job-server) : Add default driver-mode to application.conf and fix bug without default value

doc/troubleshooting.md
This would help users to understand why they are not seeing results after a
spark jobserver restart and it is expected. See issue #769
=> doc(troubleshooting): Add note on results cache for SJS restart

build.sbt, job-server-extras/src/main/java/spark/jobserver/JHiveTestJob.java, job-server-extras/src/main/java/spark/jobserver/JHiveTestLoaderJob.java, job-server-extras/src/main/java/spark/jobserver/JSqlTestJob.java, job-server-extras/src/main/java/spark/jobserver/JStreamingTestJob.java, project/Dependencies.scala, project/Versions.scala
Also,
- Fix existing compile errors.
- Sort variables in `Versions.scala` for readability.
- Update shapeless to latest version.
- Make `Versions.scala` the one-stop for all version resolution rather than re-resolving them in `Dependencies.scala`.
=> Upgrade spark to 2.1.

.gitignore, job-server-api/src/main/scala/spark/jobserver/context/JavaSparkContextFactory.scala, job-server-api/src/main/scala/spark/jobserver/context/SparkContextFactory.scala, job-server-extras/src/main/java/spark/jobserver/JHiveTestJob.java, job-server-extras/src/main/java/spark/jobserver/JHiveTestLoaderJob.java, job-server-extras/src/main/scala/spark/jobserver/context/JavaSqlContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/japi/JSqlJob.scala, job-server-extras/src/test/scala/spark/jobserver/HiveJobSpec.scala, job-server-extras/src/test/scala/spark/jobserver/JavaHiveSpec.scala
- Fixed the compilation errors (Final fix for #760).
- The Java ContextFactories were not DRY enough. Fixed that too.
- Sorted contents of `.gitignore` to make it more readable. Added `*.swp` and `job-server-extras/spark-warehouse/` (generated after running `HiveJobSpec`) to it.
However, the `JavaHiveSpec` now fails with
```
java.lang.AssertionError: assertion failed: expected class spark.jobserver.JobManagerActor$Initialized, found class spark.jobserver.JobManagerActor$InitError (InitError(java.lang.NullPointerException))
```
I feel the fix for this is in the #667 PR. Though I am not sure. Can use some guidance there to get this fixed.
=> Fix compilation errors in Hive tests using TestHiveContext

.travis.yml, ci/install-spark.sh, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, notes/0.7.1.markdown
Start job server with `context-per-jvm: true` and create new context with some invalid configuration (e.g. `memory-per-node: invalid-value`. Context creation fails with some error as expected. The akka cluster becomes now unstable and don't accept new actors => its impossible to create a new context.
Mark actor as down on initialization errors and the cluster becomes stable again.
Same issue fixed in #624 at context delete.
=> fix(akka): mark actor as down on init errors

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala
**Current behavior:**
1. Create a new context in YARN mode
2. Kill YARN app or call context.stop
3. Context is now in stopped mode and not usable anymore. Job Server lists the context as active and does not allow to start a new context with same name.
**New behavior:**
Listen to context events and stop job manager actor if context get stopped. This ensures that context gets also removed in job server.
PR contains another `cluster.down` call in case that an actor gets terminated.
=> fix(akka): Stop job manager actor on context stop

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala
PR #830 works fine with spark < 2.0 and `SparkListener` as a trait.
Spark 2.0 changed trait into an abstract class: https://github.com/apache/spark/commit/7143904700435265975d36f073cce2833467e121
This breaks the spark-2.0-preview builds: https://travis-ci.org/spark-jobserver/spark-jobserver/builds/236911458#L6808
Use anonymous innerclass instead of a mixin. Should work in master branch too.
=> fix(akka): fix spark 2 compilation issues from PR 830

.travis.yml
There's an approach noted in travis-ci/travis-ci#1441 that suggests caching
various artifacts.
- [X ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
Every time test runs, artifacts are downloaded from internet which takes time.
Use travis cache support to store already downloaded artifacts.
=> fix(ci): Cache binary artifacts to avoid repeated downloads

job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/io/FileCacher.scala, job-server/src/test/scala/spark/jobserver/BinaryManagerSpec.scala, job-server/src/test/scala/spark/jobserver/io/FileCacherSpec.scala
Described here spark-jobserver/spark-jobserver#824
*Two things:*
1. The binaries DELETE endpoint returns a 500 error on successful deletion
2. The binaries DELETE endpoint does not initiate actual deletion of the cached binaries
*Two things:*
1. The binaries DELETE endpoint returns a 200 error on successful deletion
2. The binaries DELETE endpoint will now delete the cachedBinaries
=> Fix DELETE binaries endpoint and response

README.md, project/Versions.scala
Dependency versions are selected by local java compiler version rather than target java version.
* Use `JAVA_VERSION` environment variable and java compiler version to decide what dependency version are chosen (java 7 or 8 compatible). Can be used in build config via `export JAVA_VERSION=7-jdk` in `config/....sh`.
* Downgrade/change akka and postgres versions in java 7 builds.
Latest CDH 5.10 sandbox has java 7 installed...
=> misc: fix java 7 compatibility

bin/server_stop.sh
Issues:
- When `bin/server-stop.sh` is executed but no corresponding PID exists,
the dead PID file will live forever, and that blocks all next
`server-stop.sh` executions from successfully terminating the SJS process.
- Currently, there is no check of process termination after
`kill-process-tree.sh` execution.
Fixes:
- Remove the PID file in case the mentioned process does not exist.
- Make sure that the process terminated after `kill-process-tree.sh`.
- [X ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [No ] Tests for the changes have been added (for bug fixes / features) ?
- [No ] Docs have been added / updated (for bug fixes / features) ?
- When …
=> fix(bin): make sure that PID is valid and process ended by server_stop.sh

README.md, job-server/src/main/scala/db/h2/migration/V0_7_3/V0_7_3__Migrate_Blobs.scala, job-server/src/main/scala/db/postgresql/migration/V0_7_3/V0_7_3__Migrate_Blobs.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/slick/unmanaged/UnmanagedDatabase.scala, job-server/src/test/scala/spark/jobserver/io/FlywayMigrationSpec.scala, project/Dependencies.scala, project/Versions.scala
- [x ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [x ] Tests for the changes have been added (for bug fixes / features) ?
existing tests have good test coverage for the new code
- [x ] Docs have been added / updated (for bug fixes / features) ?
**Current behavior :** (existing issues : #876)
On H2 and Postgresql BYTEA column type is used to store binaries via byte array in Scala code
Use column type BLOB on H2 and OID on Postgresql to store binaries using the large object type supported by the respective database platform. Use JDBC BLOB API for managing large object content.
In the Scala code binaries are still passed as byte arrays. This should be improved in a …
=> Blob storage

README.md, job-server/src/main/scala/spark/jobserver/WebApi.scala
The "context" endpoint offers a PUT method that allows shutting down all active contexts at once.
Currently, the PUT request will not be returned until all contexts have been shut down.
An optional "sync" parameter allows requesting the shut down of all context and returning before the request have been executed. 
=> feat(api): asynchronous context reset

README.md, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
Currently, you can't easily get the URL of the web API or other info about a context
This adds a route to retrieve information about a context, `GET /contexts/<name>` which returns some info. At the moment, this is primarily just the spark web UI url
No breaking changes
=> feat(webapi): add route for getting context info

README.md, job-server/src/main/scala/spark/jobserver/DataManagerActor.scala, job-server/src/main/scala/spark/jobserver/io/DataFileDAO.scala, job-server/src/main/scala/spark/jobserver/routes/DataRoutes.scala
* Add support for deleting all uploaded files at once through PUT method in "data" endpoint
* Update docs
The "data" API now supports a PUT method request that allows deleting all uploaded files at once.
This is in line with the "reset" functionality already available for the "context" endpoint.
Asynchronous execution is also supported. 
=> feat(api):add delete all data endpoint

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/LocalContextSupervisorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
* Create JobDAO methods for selecting and cleaning zombie jobs
* Implement methods in all implementation; Cassandra one requires new tables
* Make supervisor run cleanup of running job for context when its manager dies
BREAKING CHANGES :
* Cassandra schema change required
- [*] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [*] Tests for the changes have been added (for bug fixes / features) ?
- [*] Docs have been added / updated (for bug fixes / features) ?
Docstrings for new methods.
#757, #856, #109
When fatal error occurs during job, JobManager terminates and job is left in RUNNING state forever.
When fatal error occurs during job, jobs are …
=> fix(job-server) clean running jobs after context JobManager dies

job-server-api/src/main/scala/spark/jobserver/api/SparkJobBase.scala, job-server-extras/src/test/scala/spark/jobserver/JavaSessionSpec.scala, job-server-extras/src/test/scala/spark/jobserver/JavaStreamingSpec.scala, job-server-extras/src/test/scala/spark/jobserver/NamedObjectsJobSpec.scala, job-server-extras/src/test/scala/spark/jobserver/SessionJobSpec.scala, job-server-extras/src/test/scala/spark/jobserver/StreamingJobSpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonJobManagerSpec.scala, job-server-tests/src/main/scala/spark/jobserver/RemoteDataFileJob.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/DataManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/io/DataFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/RemoteFileCache.scala, job-server/src/test/scala/spark/jobserver/DataManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JavaJobSpec.scala, job-server/src/test/scala/spark/jobserver/JobInfoActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/JobSpecBase.scala, job-server/src/test/scala/spark/jobserver/LocalContextSupervisorSpec.scala
Files uploaded via Data API (`/data`) are stored on the host running the REST frontend and can't simple accessed by driver instances on other hosts in the cluster.
Files can now accessed via `JobEnvironment` and are transferred via akka:
```scala
def runJob(sc: SparkContext, runtime: JobEnvironment, input: JobData): JobOutput = {
runtime match {
case remote: DataFileCache => remote.getDataFile("...")
case local => Files.read.. // job does not support remote files
}
```
Local copies are removed on jvm/context shutdown and on file delete against the REST API.
No public interfaces changed. Jobs compiled against older job server version should work without any changes.
---
This change is [<img …
=> feat(jobenv): Remote data file cache

doc/troubleshooting.md
Add some more infos how to handle empty result (might be related to #930 and #931).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/934)
=> doc(troubleshooting): improve ,,no result'' section in troubleshooting guide

bin/manager_start.sh, job-server/config/docker.conf, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala
* Add logging when starting context through manager_start.sh
* manager_start.sh process is now fully asynchronous
* spark-submit logs routed to main application logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/918)
=> fix(job-server): fix for 916,917: logging for manager_start.sh

job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
Remove unused getJobConfigs from all over. Due to
performance reasons it was deprecated and doing
new changes to some parts of *DAO require changes
to this part, which is not cool.
Here is the PR which deprecated this function
https://github.com/zromi18/spark-jobserver/commit/005cfbc516d91ad3406099386dea04ebbc5992cb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> refactor(jobserver): remove deprecated getJobConfigs

README.md, doc/jmx.md, job-server/src/main/scala/spark/jobserver/JobCache.scala
A helpful metric to see the current job cache size.
N/A
A new job-cache metric is exposed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/944)
=> feat(jobserver): Add JMX metric for job cache

job-server/src/main/scala/spark/jobserver/JobCache.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
Mesos cluster change[1] introduced this redundant
caching and can be safely removed. Now, FileCacher
is the only class responsible for caching jars. The
discussion regarding the consent of stakeholders is
here [2].
Also removing all the instances of GetBinaryContent
because it was only used by redundant change.
This change was tested with client and cluster mode.
[1] https://github.com/spark-jobserver/spark-jobserver/pull/681/files
[2] https://github.com/spark-jobserver/spark-jobserver/commit/9084053cf6b09e02ce8c148af7745f8182cc0755#commitcomment-25033986
If this PR …
=> refactor(jobserver): Remove redundant caching code

job-server/src/main/scala/spark/jobserver/WebApi.scala
Add explicit deletion timeout for StopContext message.
In #727 there was a contextDeletionTimeout added which determines how
long we wait for a context to stop. WebApi does not respect this timeout
though, implicit timeout for StopContext message is much shorter than
actual contextDeletionTimeout. Fix by adding explicit timeout for
StopContext message.
WebApi timeouts for StopContext message sooner that actual stop-context timeout 
(contextDeletionTimeout)
WebApi timeouts StopContext after contextDeletionTimeout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/951)
=> fix(webapi): add missing context deletion timeout

README.md, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/util/SSLContextFactory.scala
* Support for certificate based client authentication
* Updated docs
Support for certificate based client authentication. 
Client authentication can be enabled by pointing Job Server to a JKS file and providing a valid password through the application.conf file.
When enabled, client certificate validation is enforced, meaning Job Server will refuse connections that do not provide a valid client certificate.
**Other …
=> feat(job-server): Client authentication

README.md, build.sbt
Assembly in job-server module without extras doesn't make much sense; that will not allow most jobs to run.  Explicitly disable the assembly to limit user errors, and clarify as such in the README.
See #957 for example and many others.  Right now if someone does `sbt assembly` of all modules then an assembly from both job-server and job-server-extras is generated, leading to confusion. Furthermore the `job-server` assembly sometimes errors out.
Assembly jar from `job-server` module is no longer built.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/959)
=> misc(build): disable assembly in job-server module

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/resources/local.test.jobsqldao.conf, job-server/src/test/resources/local.test.jobsqldao_dbcp.conf, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
Currently as soon as the jar is upload using /binaries
endpoint, it is cached on filesystem. On a high usage
SJS, disk is important and a trend has been seen where
users upload jars but don't start jobs. This change
gives the option to admin to cache jars on job start
only.
The property "spark.jobserver.cache-on-upload" is
configurable and can have the value true/false.
**Current behavior :** As soon as the jar is upload using /binaries
endpoint, it is cached on filesystem.
**New behavior :** If the property "spark.jobserver.cache-on-upload" is set to false, jar will be only cached on job start. …
=> feat(jobserver): Enable/disable jar caching on upload

job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
* Return 404 in case of deletion of non existing binary
* Add test for this case
If someone tries to delete non existing binary, exception is thrown.
This behavior differs from the behavior of contexts and jobs in the same situation, they return 404
Return 404 in case of deletion of non existing binary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix(jobserver): return 404 for deletion of non existing binary

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
If for some reason driver JVMs loose connection with
master, driver JVMs keep on running forever without
any chance of recovering. This change adds a watch on
master. If master goes down or network break, the driver
JVMs kill themselves.
If driver looses connection to master, it marks master node as DOWN and becomes a zombie. The process keeps on hanging until kill command is executed manually.
- If connection loses, the driver will kill itself after 30s of inactivity.
- By default, this behavior is disabled. It can be enabled by turning the config property to …
=> feat(jobserver): Kill zombie context JVMs

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
PR #869[1] introduced a new route for getting context information. This
change adds the field "applicationId" to this context information.
Refactoring:
Before classes like GetSparkWebUIUrl, NoSparkWebUI, SparkWebUIUrl, ..
were used to expose the context information. But now not only the
context UI url is exposed, so the names of these classes were changed to
more generic names.
[1] #869 feat(webapi): add route for getting context info
Change-Id: If04c2591fae40d1d872d2236c8b9dbef13bf28e9
See commit message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1013)
=> feat(webapi): Add application id to route /contexts/<context>

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
Steps:
- Create one akka cluster for master at port 2552
- Create slave akka cluster at random port
- Create a fake jobmanager actor
- Override launchDriver method and instead of
creating a new JVM, create a cluster and JobManagerActor
in the same process. This newly created actor is
used for communication with master
Since, creating a cluster is expensive, we create the
cluter only once and reuse it for each testcase.
All the contexts that we create during a testcase, we
remove them in after{} block afterwards. This makes
sure that each testcase has a clean start.
There are no testcases for …
=> test(jobserver): Add testcases for AkkaClusterSupervisor

job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
This solution is ugly as it changes the testcase rather the actual behavior. In an upcoming change, I will fix this wrong behavior correctly. This change is just to have a stable tests in master branch.
As per the current behavior of AkkaClusterSupervisor, if a context
is stopped, a ContextStopped message is sent back to the user but
the data related to context is not removed right away. It is cleaned
up in Terminated event. Now during this time, if the same context
is created again, the user will receive ContextAlreadyExists message.
This behavior needs to change. To make the current …
=> fix(jobserver): Fix randomly failing testcase in AkkaClusterSupervisorSpec

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/util/Environment.scala, job-server/src/main/scala/spark/jobserver/util/Launcher.scala, job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala
spark.driver.memory parameter should have a
valid -Xmx style string e.g. 1024m, 2g.
If the spark.driver.memory parameter has an
invalid format, SparkLauncher will
still accept this value but during the startup
of JVM it will throw exception.
At this point, it is too late because master has
no control. The request that user sent to create
context will just timeout. To avoid this, during
validation phase a check is added and approriate
error message is shown to user.
* Add testcases for ManagerLauncher
* Extend SparkLauncher to get control during testing
* Add new trait named Environment with 2 concrete
implementations
**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull …
=> feat(jobserver): Allow valid memory value and add testcases for ManagerLauncher

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, job-server/src/test/scala/spark/jobserver/LocalContextSupervisorSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
This change is related to
https://github.com/spark-jobserver/spark-jobserver/issues/1040
* Instead of using "contexts" hash map, the data from DB is used to
get/save the actor reference and to get/save the state of the context.
* The "STARTING" state is added for the interval between the start
request and the actual start of the context.
* The reference of each JobManager actor is stored in the database. Due
to this, it is possible to reconnect to a running SJS Driver, if the SJS
Master has crashed.
This change introduces a check for running SJS Drivers on the startup
phase of SJS Master.
**New behavior …
=> feat(jobserver): move data from contexts hash to db

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
Since, we have a DB table for context now, we don't
need to put the context config and is-adhoc flag in
the hashmap anymore. Now, we pull this information from
DB.
This hashmap also contains the success and failure
callbacks. It doesn't make sense to put them in DB
because they are just temporary. If somehow the master
crashes, the user who is waiting for the response
won't get the response anyway. …
=> feat(jobserver): Remove extra states from contextInitInfos

job-server-extras/src/test/scala/spark/jobserver/JavaStreamingSpec.scala, job-server-extras/src/test/scala/spark/jobserver/StreamingJobSpec.scala, job-server/src/main/scala/db/h2/migration/V0_7_8/V0_7_8__add_contextId_and_state_to_jobs.scala, job-server/src/main/scala/db/migration/V0_7_8/Migration.scala, job-server/src/main/scala/db/mysql/migration/V0_7_8/V0_7_8__add_contextId_and_state_to_jobs.scala, job-server/src/main/scala/db/postgresql/migration/V0_7_8/V0_7_8__add_contextId_and_state_to_jobs.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobInfoActor.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobStatusActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/JobInfoActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobStatusActorSpec.scala, job-server/src/test/scala/spark/jobserver/LocalContextSupervisorSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala, job-server/src/test/scala/spark/jobserver/auth/WebApiWithAuthenticationSpec.scala, job-server/src/test/scala/spark/jobserver/io/FlywayMigrationSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
This change is related to
https://github.com/spark-jobserver/spark-jobserver/issues/1040
With this change the relation between context and jobs table is fully
defined
* Implement migrations for h2, mysql and postgres
* Reflect new schema changes in JobSqlDAO, C*DAO, InMamoryDAO and
FileDAO
* Persist job's state and contextId in DAO
* Use state from DAO instead of old state calculation
* Add tests in C*/SQL DAO spec to cover the new DAO function
* Add test to cover the changes inside JobManagerActor
* Add tests for JobStatusActorSpec/JobInfoActorSpec
---
This change …
=> feat(jobserver): Add CONTEXT_ID and STATE to the JOBS table

doc/cluster.md, doc/mesos.md, doc/supervise-mode.md, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
#1040
Currently, if a job is restarting and the user submits
/jobs, figuring out the restarting scenario is not too
obvious by just looking at the output.
User needs to know that if state is ERROR, error msg is
Context Terminated exception and supervise mode is
enabled for that context, only then it will be restarting.
The /contexts endpoint only shows contexts in state "RUNNING". 
If the reconnect failed, the state of the context is set to error, but the state of jobs which were running
in this context isn't touched.
This PR adds an explicit state ("RESTARTING") which is also shown in /jobs.
The /contexts endpoint will also show contexts in state "RESTARTING".
If the reconnect failed, the state of jobs which are …
=> feat(jobserver): Add restarting state and improve reconnect logic

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobStatusActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobStatusActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala
This PR contains various fixes, which aren't worth to be requested in separate PRs.
- [ X] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ X] Tests for the changes have been added (for bug fixes / features) ?
- [ X] Docs have been added / updated (for bug fixes / features) ?
* The state of jobs with unprocessed states on context termination will be set to error.
* If a context will be deleted, the context status will always be changed to "STOPPING" state if the information and reference of this context is found. But the state should not be changed if it is a final state (we define final states as "FINISHED", "ERROR" and "KILLED").
* If supervise mode is enabled and …
=> Various fixes

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/test/scala/spark/jobserver/JavaJobSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
**Current behavior:**
Every job exceptions wrap in the RuntimeException.
**New behavior:**
Exception remains unchanged.
This is the fix for #989 All changes are just revert of #408 In the issue I asked about motivation behind #408, but I got no answer. So, I assume that I could just revert this changes, If there is no real motivation behind them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1091)
=> feat(job-server): revert wrapping all exceptions in the RuntimeException

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
The response of GET context/<name> contains now the whole context object from the database except the context configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1089)
=> feat(jobserver): return also information from db for GET context/<name>

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
If context fails to restart it results in an ERROR state for a context,
but jobs inside keep RESTARTING state. This fix changes the behaviour to
also change the state of related jobs and tests it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1102)
=> fix(jobserver): change also job states if context fails to restart

Dockerfile.test, build.sbt, doc/EMR.md, project/Assembly.scala, project/ExclusionRules.scala, project/Release.scala, project/build.properties, project/plugins.sbt
I noticed that the current version of sbt in this project was 0.13.12, which is very old. In this pull request, I updated sbt to the latest 1.1.6 version. Some additional points:
* All deprecation warnings were fixed.
* Docs was updated.
* Build scripts were updated.
Also, I updated all sbt plugins to the latest versions. Most of the updates didn't require additional work. But some did:
* `"me.lessis" % "bintray-sbt"` was renamed to `"org.foundweekends" % "sbt-bintray"`
* I completely removed `ls-sbt`, because all implicitly stuff is abandoned now. After this deletion `JobServerRelease` object has only `ourReleaseSettings` field. And I decided to rename `JobServerRelease.ourReleaseSettings` to `Release.settings` because it's less verbose and more clear IMO.
* I …
=> misc(all): Update sbt to 1.1.6 and update sbt plugins

doc/job-server-flow.md, job-server-extras/src/main/scala/spark/jobserver/StreamingTestJob.scala, job-server-extras/src/test/scala/spark/jobserver/StreamingJobSpec.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/CommonMessages.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobSpecBase.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, scalastyle-config.xml
This PR is divided into 6 commits for easy review. Each commit contains details in the commit message.
Summary:
If a user submits DELETE /context/<name> and the context is stuck or stop is still in progress, the DELETE /context request timesout. Jobserver loses control of this JVM and user has no way to figure out though SJS api what happened.
With this change, we introduce a more graceful method of deletion. If the context stops within the timeout, the same behavior is kept i.e. 200 response code with message saying "Context Stopped". If the request times out, we send back 202 Accepted …
=> feat(jobserver): Handle DELETE /context gracefully

job-server/src/main/scala/spark/jobserver/io/FileCacher.scala, job-server/src/test/scala/spark/jobserver/io/FileCacherSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
File name for cached binaries currently uses 12h format for the hour part of the timestamp, e.g. `job-20161010_010000_000.jar` for timestamp "2016-10-10T13:00:00Z".
File name for cached binaries now uses 24h format for the hour part of the timestamp, e.g. `job-20161010_130000_000.jar` for timestamp "2016-10-10T13:00:00Z".
Not breaking per se, though worth noting: after upgrading, cached binaries for binaries uploaded in the afternoon will no longer be found and will be re-cached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1130)
=> fix(job-server): use 24h format for cached binary file name

bin/server_deploy.sh
When deploying jobserver with different configurations names,
previous configuration files are kept in deploy folder.
But server_start.sh script is taking just the first found configuration.
When uploading new deployment, remove old configuration files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1135)
=> Remove old configs before new deployment

bin/setenv.sh, build.sbt, job-server/config/local.sh.template, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/util/HadoopFSFacade.scala, job-server/src/main/scala/spark/jobserver/util/Launcher.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/util/HDFSClusterLike.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala, project/Dependencies.scala
Standalone cluster with cluster mode requires
users to provide config/jar file on each worker through
file system or hadoop supported filesystems.
According to spark documentation:
"If your application is launched through Spark submit,
then the application jar is automatically distributed
to all worker nodes"
The above statement is not correct.
* If the driver folder doesn't exist on the worker, then
spark will create the folder and download the jar file
from any method that user has provided (file/hdfs/s3).
* If the driver folder already exists then Spark will
just use the already existing jar.
Further, according the Spark documentation, the configuration
"spark.files" will place the files in the working
directory of executors. …
=> feat(jobserver): Load config and jar from hadoop

README.md
Previously only 200 OK was mentioned in the README which is not an accurate response for uploading a JAR. Changed it based on my recent observation of response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1139)
=> Update response of JAR Upload

job-server/src/main/scala/spark/jobserver/io/FileCacher.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
**Current behavior** :
RetrieveBinaryFile, FetchAndCacheBinFile function are in JobSqlDAO and in JobCassandraDAO.
RetrieveBinaryFile checks for the file path and if doesn't find a file, then caches and fetches it using FetchAndCacheBinFile.
**New behavior**:
- Add getPath function to FileCacher and decide on cache based on it (also adds a layer of abstraction). Remove FetchAndCacheBinFile.
- Rename retrieveBinaryFile to getBinaryFilePath
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1144)
=> Refactor file caching

README.md
As /jars path is deprecated, use binaries path in WordCount example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1146)
=> Update jar upload path in documentation

Dockerfile.test, README.md, ci/install-spark.sh, job-server-extras/src/test/scala/spark/jobserver/python/PythonSparkContextFactorySpec.scala, job-server-python/src/python/run-tests.sh, job-server-python/src/test/scala/spark/jobserver/python/SubprocessSpec.scala, project/Dependencies.scala, project/ExclusionRules.scala, project/Versions.scala
Note: Currently, docker part is not verified.
Due to update, multiple testcases failed with
NoSuchMethodError with following errors
- io.netty.buffer.PooledByteBufAllocator.metric()
Netty was updated to fix this.
- net.jpountz.lz4.LZ4BlockInputStream.<init>
cassandra-unit dependency was bringing old version
of lz4 which was 1.3.0. Spark upgraded this library
in new version and cannot work without 1.4.0. So,
excluded the 1.3.0 from cassandra-unit.
https://issues.apache.org/jira/browse/SPARK-21276
- ImportError: No module named py4j.java_gateway
Updated the py4j version to 0.10.7, the hint for
this version comes from what Spark package internally
uses. Inside spark 2.3.2 package, the right py4j
version can be figured out by going to
spark_package_dir/python/lib/
Tests:
Executed a simple …
=> fix(core): Update Spark version to 2.3.2

README.md
Remove version from "Spark Job Server is now included in Datastax
Enterprise 4.8!" since 4.8 is now EOL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1147)
=> Adjust Users list in readme.md

project/Dependencies.scala, project/ExclusionRules.scala, project/Versions.scala
* The rule is excluding and adding the same version of the library (Spark 2.3.2 depends on netty-all 4.1.17: https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.11/2.3.2)
* ExclusionRule seem to be broken (using artifact property instead of name)
Remove exclusion rule at all
https://github.com/spark-jobserver/spark-jobserver/issues/1150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1152)
=> Remove netty-all exclusion rule

.gitignore, bin/ec2_deploy.sh, bin/ec2_destroy.sh, bin/kill-process-tree.sh, bin/server_deploy.sh, bin/server_host_setup.sh, bin/server_package.sh, bin/server_start.sh, bin/server_stop.sh, bin/setenv.sh, run_tests.sh
- Use shebang with env (#!/usr/bin/env searches PATH for bash, which may be not /bin/bash)
- Ignore job-server .sh configs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1168)
=>  Minor fixes in gitignore and scripts shebang

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1156)
=> feat(job-server): pass context name as appName when context is submitted

project/Versions.scala
As pointed by @TharinduAmila and confirmed by
version compatability metrics on
https://github.com/datastax/spark-cassandra-connector#version-compatibility
, the  version of C* connector should be 2.3
for Spark 2.3.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1170 …
=> fix(jobserver): Upgrade C* connector version

job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/util/MeteredHttpService.scala
This very small PR gives a bit more insight into the usage of the WebAPI, here specifically tracking the amount of read/write requests. Also makes it easier to add similar things for the WebAPI in the future.
* Add MeteredHttpService that tracks metrics for number of read/write requests
* Let WebAPI extend new MeteredHttpService
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1178)
=> feat(jobserver): Add counters for API requests

job-server/src/test/scala/spark/jobserver/JobSpecBase.scala
Currently, the frequency of failing tests is high. Internally, we use tests which need to communicate with Akka messages and if some message don't arrive due to slow build system, the tests fail.
Should improve the situation. If it doesn't help then we need to look at individual tests to fix them.
--- …
=> Adapt test configurations to run on slow build system

job-server-tests/src/main/scala/spark/jobserver/SparkTestJobs.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
`Future` only completes on success or when encountering a `NonFatal`
error; when encountering a fatal error, the future does not complete at
all and the error is passed to the execution context.
This change wraps all `Throwable` so the `Future` can complete and the
`Failure` handlers can cleanup the job and properly mark it as failed.
#1161 
When a fatal error occurs in a job, the `JobManagerActor` is now able to properly mark it as failed and cleanup.
--- …
=> fix(jobserver): ensure job cleanup after fatal error - ref #1161

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala
* Increase timeout for GetSparkContexData in WebAPI from default
short Timeout to 15 seconds. The short default timeout resulted
in a status code 500 (AskTimeoutException) sometimes when querying
stopped contexts.
* Decrease timeout for GetContextData in AkkaClusterSupervisorActor
from 30 seconds to 10 seconds (seemed very generous before)
Querying a stopped context (sometimes taking additional time because it queries the spark backend) can result in an unnecessary status code 500 because of the tight timing. Timeouts in the internal logics are set higher anyways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobse …
=> fix(jobserver): Align GetSparkContexData query timeouts

job-server/src/main/scala/spark/jobserver/JobServer.scala
Example:
In cluster mode, if a to-be-joined actor is picked that goes down shortly after the jobserver sees it as UP, things issues like #1157 can occur.
When the master joins an existing cluster on an unreachable node, a retry on other nodes (that were also seen as UP during startup) is possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1193)
=> fix(jobserver): Fix unlimited cluster.join request

akka-app/src/main/scala/spark/jobserver/common/akka/web/CommonRoutes.scala, akka-app/src/test/scala/spark/jobserver/common/akka/web/CommonRoutesSpec.scala
Expose mean additionaly to median and other percentiles since the mean provides more insight into the overall distribution of timer values.
This distribution is interesting especially for API request durations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1192)
=> feat(akka-app): Expose mean duration of timers in metricz API endpoint

job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala
In some special cases unused binaries were kept in the DB.
For example: Consider the following 3 binaries in the DB:
1) Name - "appA", Hash - 123
2) Name - "appA", Hash - 456
3) Name - "appB", Hash - 123
If someone would try to delete binary with the name "appA", the names
would be deleted, but not the binaries themselves. It means that binary
with hash "456" would still be available in the "binary_contents" table
and there would be no possibility to delete it.
Other scenarios:
1- If user deletes appA then app should be deleted but binary
in binary contents table should remain.
appA hash1
appB hash1
appC hash2
2- If user delets appA then both hashes/bin should be cleaned
from binary contents table
appA hash1
appA hash2
3- If user deletes appA then appB and hash/binary for appB should …
=> fix(jobserver): keeping unused binaries

Dockerfile.test, ci/install-python-dependencies.sh
**Current behavior :**  Travis build failing
It seems that the tag 8 of java is not available
anymore on dockerhub because the team maintaining
it has deprecated the java:8.
instructure/dockerfiles@aad60a3
Here are all the available tags
https://hub.docker.com/r/instructure/java/tags
Since "instructure" does not has many downloads,
there are good chances that they deprecate again.
So, using a famous java8 container from openjdk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1204)
=> fix(travis): Update base container tag 

job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/ZookeeperUtilsSpec.scala, job-server/src/test/scala/spark/jobserver/util/CuratorTestCluster.scala, project/Dependencies.scala, project/ExclusionRules.scala, project/Versions.scala
Jobserver jar is started with spark-submit command and because
of this jobserver is using Curator library version imported
by Spark.
As we don't use any specific Curator features introduced after
2.6.0, the easiest option will be to downgrade to match
Curator dependency of Spark 2.3.2. The dependency will be
now marked as provided, because we will use the library
from Spark. Downgrade is also important so that our tests
are made for the right version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1206)
=> Downgrade zookeeper version and remove not needed ZK test helper

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala, job-server/src/test/resources/local.test.combineddao.conf, job-server/src/test/scala/spark/jobserver/io/CombinedDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/ZookeeperUtilsSpec.scala
Zookeeper timeout setting may vary depending on cluster (number of nodes particularly), so it makes sense to have them in config file for DAO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1211)
=> Make zookeeper settings configurable

job-server/src/main/scala/spark/jobserver/util/Utils.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/SqlCommonSpec.scala
saveJobConfig function in JobDAO has Unit return
value. This means that if we save a config
and read it again in next line then it boils down
to timing and the test becomes flaky.
This change adds a retry while reading the config
to fix the test.
Further, SqlCommonSpec uses the saveJobConfig from
SqlCommon which has a return value. So, in this
test, we just add Await.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1210)
=> fix(tests): Fix saveJobConfig tests

job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/io/MetaDataDAO.scala, job-server/src/main/scala/spark/jobserver/io/MetaDataSqlDAO.scala, job-server/src/main/scala/spark/jobserver/io/SqlCommon.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/test/scala/spark/jobserver/BinaryManagerSpec.scala, job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala, job-server/src/test/scala/spark/jobserver/io/CombinedDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, job-server/src/test/scala/spark/jobserver/io/MetaDataSqlDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala, scalastyle-config.xml
Currently, user is allowed to delete a binary even
if the binary is being used by a job. Deletion
leads to 2 cases
- Once the jobs finishes, a message is sent to
JobStatusActor which tries to persist the state to
dao but fails because saveJobInfo tries to query
binaries table for binId but since the binary is
deleted, query fails and status is not saved.
- During restart scenario, driver tries to restart
the job and needs binary. Since, binary is deleted
the job cannot be restarted.
The fix for this is to not allow deletion of binary if an active job is using it.
If …
=> Remove binaries if not used & adding logging to webapi

job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala, job-server/src/main/scala/spark/jobserver/util/JsonProtocols.scala, job-server/src/main/scala/spark/jobserver/util/Utils.scala, job-server/src/test/scala/spark/jobserver/util/JsonProtocolsSpec.scala
**Content**
These are some production-tested fixes/improvements for the recently introduced MetadataZookeeperDAO, mainly:
- Increase verbosity of ZK dao logs to get a bit more insight
- Make date parsing of ZK dao thread safe, as this lead to exceptions in date parsing in the past
- Adapt one timeout so that potential zookeeper bottlenecks do not result in TimeoutExceptions
See commit messages for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1216)
=> ZookeeperDAO fixes

doc/dao-setup.md, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/AutoPurgeActor.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/test/resources/local.test.combineddao.conf, job-server/src/test/scala/spark/jobserver/io/zookeeper/AutoPurgeActorSpec.scala
Due to the hierarchical nature of our zookeeper schema, read queries require to iterate over all nodes and process each of them. Especially within a distributed setup large amounts of Zookeeper
nodes can therefore reduce Jobserver performance.
This commit introduces an option to automatically remove old contexts and jobs to contain this effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1220)
=> Introduce Zookeeper Autopurge mechanism

job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala
This feature was introduced to
a) Keep a consistent version of BinaryInfo at the JobInfo object
(already addressed by commit:
"fix(jobserver): Create Job with full BinaryInfo information").
b) Mimic behavior of the JobSqlDAO that removes with missing
binaries during join, which seems like this is actually unintended 
in SQL as well.
Removing this query does also improve performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1223)
=> fix(jobserver): Remove refreshBinary for Zookeeper

job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala
In case the resolution of a JobManagerActor in cluster mode fails
based on ContextInfo in the database, the context and associated
jobs are set to state 'error'.
With Zookeeper, if a lot of such updates are performed (which can
happen during update of big clusters), the linear nature of a
(by sync) consistent Zookeeper may lead to queued requests,
which makes the latest requests take longer.
Instead of performing these updates parallel in futures, this is
now done sequentially, so that timeouts are not compromised by
earlier operations.
* Replace ask oncomplete with Await.ready in one instance
* Adapt test to run blocking call in a parallel thread
Change-Id: I80ac6ebde3bcd168c8164900a98067e9f76ca491
---
This change is [<img …
=> fix(jobserver): Persist error state sequentially during startup

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/main/scala/spark/jobserver/util/DAOCleanup.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, job-server/src/test/scala/spark/jobserver/util/DAOCleanupSpec.scala
When contexts are set to error because of a ForkedJVMInitTimeout, no end_time was set.
- end_time is now set correctly
- There is a configurable cleanup routine for zookeeper which does some maintenance tasks during startup if requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1229)
=> fix(jobserver): Properly set end_time on ForkedJVMInitTimeout 

job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala
**Current behavior:** 
I noticed there is a flaky CassadraDAOSpec test:
```
[info] - should store context with actor address and endtime (9 milliseconds)
[info] - should update the context if id is the same for two saveContextInfo requests *** FAILED *** (45 milliseconds)
[info]   ContextInfo(c731f756-8f7f-4e5a-8759-f251de646f91,test-context3,,None,2019-06-29T11:17:31.598Z,None,STARTED,None) was not equal to ContextInfo(c731f756-8f7f-4e5a-8759-f251de646f91,test-context2,,None,2019-06-29T11:17:31.597Z,None,STARTED,None) (JobCassandraDAOSpec.scala:446)
```
The test overwrites one context with a new value, but the problem is that contexts in Cassandra are ordered by StartTime. 
The new and old value created in two consequent lines of code (and new value before the …
=> CassandraDAOSpec: Fix of flaky test and small refactoring

build.sbt
**New behavior:**
The Cached Resolution feature is akin to the incremental compilation,
which only recompiles the sources that have been changed since
the last compile. Unlike the Scala compiler, Ivy does not have
the concept of separate compilation, so that needed to be implemented.
Instead of resolving the full dependency graph, the Cached Resolution
feature creates minigraphs — one for each direct dependency
appearing in all related subprojects. These minigraphs are
resolved using Ivy’s resolution engine, and the result is stored
locally under ~/.sbt/$SBT_VERSION/dependency/
After all minigraphs are resolved, they are stitched together
by applying the conflict resolution algorithm (typically picking
the latest version).
When you add a new library to your …
=> feat(sbt): Use cached resolution

README.md, bin/ec2_example.sh.template, doc/job-server-flow.md, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/auth/WebApiWithAuthenticationSpec.scala
**New behavior:**
The path is long time deprecated and not supported.
As already a new version of Jobserver with the deprecated path
was released, the path can be finally removed from the
WebApi to clean up the code a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1234)
=> refactor(webapi): Deprecate WebAPI /jars path

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, project/Dependencies.scala
Following the [HA proposal mentioned in issue #1236](https://github.com/spark-jobserver/spark-jobserver/issues/1236), this singleton change represents step 3/5 to achieve jobserver HA:
**Details**
* Create AkkaClusterSupervisorActor as an akka cluster singleton
on jobserver startup
* Adapt application.conf for a cluster singleton
* Adapt JobserverSpec to also check for singleton infrastructure
in case of context-per-jvm=true
* Temporarily adapt changes to jobManager zombie kill features as
long as we have no split brain resolver.
In jobserver HA mode the logic following a MemberUp event
(initializing a context) or Terminated event (updating context
and associated job states in the database) can conflict when
handled by two or more active jobservers. Moving this logic to a
cluster …
=> feat(jobserver): Make AkkaClusterSupervisorActor a singleton

job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala
Custom exceptions should extend Exception class with `Exception(msg)` constructor, otherwise exception.getMessage function will return null.
This is especially important for ZookeeperDAO as the null value of the exception message breaks ContextInfo deserialization. Also a new test case for Zookeeper was added (checking that it is possible to save context with custom context exception).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1240)
=> fix(jobserver): Fix custom exceptions constructor

job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/main/scala/spark/jobserver/util/Utils.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, job-server/src/test/scala/spark/jobserver/util/UtilsSpec.scala
With recent changes, spinning up multiple
jobserver instances is possible. This change
adds required changes to setup an HA jobserver
cluster.
The address(es) can be specified in comma
separated format in spark.jobserver.ha.masters
section.
At startup, jobserver automatically forms
a new cluster with all the masters or joins
the old cluster of slaves. While forming the
cluster for the first time, the first node
shouldn't fail to come. If it does then the
secondary node will be hanging forever.
kill-context-on-supervisor-down is used in
client mode for killing the slaves if supervisor
is down. This was implemented because at the
time, we didn't had any good split brain resolver.
We were relying on auto-down to mark the node
as DOWN and kill-context-on-supervisor-down to
actually kill the …
=> feat(jobserver): Add HA setup for jobserver

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
If the context in stopping state will be restarted by Spark,
jobserver should kill the new instance of this context,
put context in FINISHED state and clean up all the jobs for
the context.
One of problematic scenarios:
Context is into the load and stops responding to Akka
heartbeats. At the same moment AkkaClusterSupervisor
receives stop request for this context, but can't
send it to the context. Context stays in STOPPING
state. Due to the load on the driver/restart of the
node or something else, context can be restarted by
Spark. Before the fix it was allowed to join the cluster
and was changing stopping context back to RUNNING state.
--- …
=> fix(jobserver): Don't allow STOPPING context to restart

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
Previously watches for existing contexts were added by sending a
RegainWatchOnExistingContexts message to the supervisor on
Jobserver startup.
For an HA/singleton setup, if a second singleton instance takes
over because of failure/restart of the first jobserver, there
are no watches created for the existing contexts.
Although the startup of the previously failed jobserver will
add those watches (via proxy) to the new singleton, and this
being a relatively rare scenario with a small time window, this
could result in missing terminated events and therefore contexts
remaining in state STOPPING.
To fix this, remove the RegainWatchOnExistingContexts message
completely and query/resolve the existing contexts on singleton
startup. Drawback is that query+resolution have to be done twice
now on …
=> fix(singleton): Add watch to existing contexts automatically

akka-app/src/main/scala/spark/jobserver/common/akka/AkkaTestUtils.scala, job-server-extras/src/main/scala/spark/jobserver/SparkSessionJob.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala
Refactor the code a bit
and address some of SBT warnings:
* Cases in a match should cover all possible replies
* Timeout in AkkaTestUtils can be private val as the variable is not
changed anywhere
* Replace deprecated functions
* Remove shadowed import
Leaves warnings about SQLContext and HiveContext untouched (as there
seem to be no easy way to fix it and we need to refactor SparkContext
into SparkSession)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1250)
=> refactor(jobserver): Address SBT warnings

job-server-api/src/main/scala/spark/jobserver/context/SparkContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/python/PythonContextFactory.scala
If an error (instead of an exception) happened during job
validation, akka.jvm-exit-on-fatal-error was shutting down the
JVM without responding back to Jobserver. The request then timed
out and did not give a useful error as for the Exception cases.
* Let loadAndValidateJob functions of ScalaContextFactory and
JavaContextFactory catch Throwables (including Errors) instead
of Exceptions only.
* Extend JobLoadError case class to contain Throwable instead of
Exception
* For PythonContextFactory throwables were already caught and
wrapped to an exception. Simplified this code to directly
throw a Throwable instead of wrapping it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/s …
=> feat(api): Handle all throwables in loadAndValidateJob

job-server/src/main/scala/akka/downing/KeepOldestAutoDown.scala, job-server/src/main/scala/akka/downing/KeepOldestDowningProvider.scala, job-server/src/test/scala/akka/downing/KeepOldestAutoDownSpec.scala
Previous implementation with `sys.exit(-1)` was calling Spark shutdown hooks
and sometimes putting context in KILLED stated (depending on success of the
DAO operation).
The `java.lang.Runtime.halt(int status)` method forcibly terminates the currently
running Java virtual machine. This method never returns normally. Unlike the
exit method, this method does not cause shutdown hooks to be started and does
not run uninvoked finalizers if finalization-on-exit has been enabled.
Split brain resolver class is initialised once the cluster is created.
When cluster is in inconsistent state, node may be in a JOINING
state and never reach UP state (e.g. node was joining the cluster and
right at the same moment all other nodes in the …
=> fix(sbr): Should subscribe to events early and exit with -1 without hooks

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala
As stated in the issue (which is already closed) this check is atomic by now. Remove the comment to avoid confusion.
https://github.com/spark-jobserver/spark-jobserver/issues/349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1257)
=> refactor(jobserver): Remove outdated TODO

project/Versions.scala
Jobserver should be updated to use 2.5.x as Akka version 2.4 is already officially out of support. Nevertheless it's not supported to make rolling update of Akka directly to 2.5-M1 without upgrading to at least 2.4.16.
See [official documentation](https://doc.akka.io/docs/akka/current/project/migration-guide-2.4.x-2.5.x.html#rolling-update)
Upgrading to 2.4.20 as it's currently the last version of 2.4 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1255)
=> misc(akka): Upgrade Akka version to 2.4.20

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1263)
=> doc(readme): Remove SPARK_CLASSPATH as it's deprecated

build.sbt, job-server/src/main/scala/akka/downing/KeepOldestAutoDown.scala, job-server/src/main/scala/akka/downing/KeepOldestDowningProvider.scala, job-server/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala, job-server/src/multi-jvm/scala/akka/downing/KeepOldestAutoDownMultiJVMSpec.scala, job-server/src/multi-jvm/scala/akka/downing/KeepOldestTestDowningProvider.scala, job-server/src/test/scala/akka/downing/KeepOldestAutoDownSpec.scala, project/Dependencies.scala, project/plugins.sbt
In current SBR implementation if several nodes become unreachable, for each of them there will be an UnreachableTimeout scheduled, but all nodes will be downed together when the last scheduled UnreachableTimeout is received.
This PR fixes the problem that when the last UnreachableTimeout was canceled and the corresponding node became reachable again, the remaining unstableUnreachable nodes were not downed at all.
Introduce first multi-jvm tests for split-brain resolver class. For the easiness of testing KeepOldestTestDowningProvider is made, which instead of downing nodes sends messages to testProbe.
Regarding usage of multi-jvm package, please be aware that:
* First node in test plays the role of controller. If
first node is killed during the …
=> Fixes and multi-jvm tests for split brain resolver

README.md, job-server-api/src/main/scala/spark/jobserver/context/SparkContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/StreamingTaskFailedTestJob.scala, job-server-extras/src/main/scala/spark/jobserver/context/StreamingContextFactory.scala, job-server-extras/src/test/scala/spark/jobserver/StreamingJobSpec.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/util/JobserverConfig.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
Introduce a new property stop-context-on-job-error, which can be set to true if context termination is required after job failure. By default the value is `false`.
Additionally set the default to `true` for streaming jobs only, since Spark kills the driver if a streaming job has an error and we want the same behavior in jobserver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1256)
=> Introduce stop-context-on-job-error flag

README.md, job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/test/scala/spark/jobserver/BinaryManagerSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
The current endpoint /binaries only returns all binaries from the
DAO. It should be possible to retrieve information about a specific
binary (given an appName) as well. Especially if the amount of
binaries in the database grows the current API design is not well
suited for this use case.
* Add new message GetBinary(appName) to BinaryManager returning
BinaryInfo retrieved from the DAO.
* Add new endpoint /binaries/<appName> to the WebAPI
* Extend WebApi and BinaryManager tests accordingly
* Update documentation for API
Change-Id: Ie240a90568a4dabfae67960c873579cc57aa24de
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1273)
=> feat(jobserver): Add /binaries/<appName> endpoint

Dockerfile.test, ci/install-python-dependencies.sh
The travis build started to fail due to public key failure.
"W: GPG error: http://dl.bintray.com/sbt/debian
Release: The following signatures couldn't be verified
because the public key is not available:
NO_PUBKEY 99E82A75642AC823"
The fix was to import the key already from a source.
Once this was fixed, the build failed again due to
"pip._internal module not found" and the fix was
to upgrade the version.
The reason why these problems poped up now, is still
unknown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1281)
=> ci(jobserver): Build failing due to missing public key

job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/routes/DataRoutes.scala, job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala
This PR cleans up response codes and formats and also refactors WebApi code (renamed confusing `logAndComplete` functions, removed `errMap`, merged some functions together).
Some of the endpoints response with "OK", some with json map.
Always respond with a JSON in unified "jobserver" format (with status "ERROR", "SUCCESS").
Based on https://github.com/spark-jobserver/spark-jobserver/issues/25
I also tried first to remove any text response in case of "OK" and return just status code, but it turned out to be a bit confusing especially in case of binary upload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/sp …
=> Unify response format and codes

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
Add mapping to the old dependent-jar-parameter for the
context config. Currently posting dependent jars for the context with `dependent-jar-uris` parameter doesn't work.
More information can be found in this issue: https://github.com/spark-jobserver/spark-jobserver/issues/1151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1279)
=> fix(dependent-jars): Dependent-jar-uris for context config

README.md, doc/WebApi/README.md, doc/WebApi/swagger.yaml
Until now a complete or detailed documentation (including
available parameters, return types and examples) for the API
could not be found in one common place. The documentation of
the main features of the api was spread across different docs,
examples or code.
As an OpenAPI spec seems to be a suitable tool for that, add a
manually created swagger specification as a foundation for such
a documentation.
It can be viewed for example on:
http://editor.swagger.io/
or generated into a more readable version (.html, .md) if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1282)
=> doc(webapi): Add swagger documentation for Jobserver WebApi

README.md
The default in code was always true which was
contradicting with readme file. Now adjusting
readme file according to the code.
Change-Id: Ia63e82d694f4de688a8ef83eafe72fa93e79e3cb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1284)
=> refactor(readme): Set stop-context-on-job-error=true

Dockerfile.test, README.md, ci/install-spark.sh, job-server-api/src/main/scala/spark/jobserver/util/JobserverPy4jGateway.scala, job-server-extras/src/main/java/spark/jobserver/JSessionTestLoaderJob.java, job-server-extras/src/main/scala/spark/jobserver/SessionTestJob.scala, job-server-extras/src/main/scala/spark/jobserver/context/JavaSessionContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/context/SessionContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/python/PythonContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/python/PythonJob.scala, job-server-extras/src/test/resources/hive-site.xml, job-server-extras/src/test/scala/spark/jobserver/JavaSessionSpec.scala, job-server-extras/src/test/scala/spark/jobserver/SessionJobSpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonSessionContextFactorySpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonSparkContextFactorySpec.scala, job-server-python/src/python/example_jobs/hive_support_job/__init__.py, job-server-python/src/python/sparkjobserver/subprocess.py, job-server-python/src/python/test/apitests.py, job-server-python/src/test/scala/spark/jobserver/python/SubprocessSpec.scala, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/util/JobserverConfig.scala, job-server/src/main/scala/spark/jobserver/util/Launcher.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobSpecBase.scala, project/Dependencies.scala, project/Versions.scala
Only supports uptil 2.3.2
Support for 2.4.4 added
The PR contains 4 commits and each commit has a commit message with more details.
Disabling of Hive is not currently done for Python based contexts. I will push this change soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1283)
=> Upgrade Jobserver to 2.4.4 Spark

job-server/src/main/scala/spark/jobserver/util/ForcefulKill.scala, job-server/src/test/scala/spark/jobserver/util/ForcefulKillSpec.scala
Previously, if you have defined the spark
masters in config like
spark://master1:6066,master2:6066,
then in case of master1 being down, a forceful
kill will just return the following and never
try the kill though master2.
"Connection attempt to master1:8080 failed"
This change fixes this bug and improves
logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1297)
=> fix(jobserver): Graceful force kill if master is down

job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala, job-server/src/main/scala/spark/jobserver/io/FileCacher.scala, job-server/src/test/scala/spark/jobserver/io/FileCacherRandomDirSpec.scala
If directory specified for the file caching doesn't exist, Jobserver should create it instead of failing the operation.
As cacheBinary is a protected method, new spec class for the test of modified FileCacher version is introduced. 
Seen exception:
```
java.io.IOException: No such file or directory
````
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1298)
=> fix(file-cache): Create missing directories

job-server/src/test/scala/spark/jobserver/WebApiMainRoutesSpec.scala, job-server/src/test/scala/spark/jobserver/WebApiSpec.scala
Recently master branch started to be red and one test is particularly flaky.
This test is added in WebApiSpec and is called multiple times. Although the main reason is still unclear, the first and easy fix is to move test to WebApiMainRoutesSpec and let it execute only once.
Observed exception:
```
The future returned an exception of type: spray.can.Http$ConnectionAttemptFailedException,
with message: Connection attempt to 127.0.0.1:9999 failed. (WebApiSpec.scala:290)
```
Travis build is failing often.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1300)
=> fix(test): Deduplicate WebApi PUT contexts test

akka-app/src/main/scala/spark/jobserver/common/akka/AkkaTestUtils.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/util/JobserverConfig.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala
It can happen that node was removed from the cluster or actor system was terminated, but jobserver or driver node still continues to run. In this case, we see incorrect behaviour, failing requests to start/stop resources or a zombie context.
We need to exit jobserver master or spark driver JVMs in 2 cases:
* Actor system was terminated
* Actor system was removed from the cluster
Exiting jobserver master is a low risk operation and can be easily done in both cases.
For the driver we need to take into account the following points:
1. MemberRemoved event will be triggered also if actor system leaves cluster on it's own wish. We should try not to interfere with planned exit, therefore registerOnMemberRemoved hook waits …
=> Improve SBR shutdown logic

job-server/src/main/scala/db/postgresql/migration/V0_7_9/V0_7_9__jobinfo_contains_uris.scala
Use correct syntax to add new columns. Copy existing "BIN_ID" to "BIN_IDS".
Fill "URIS" of existing jobs with empty string.
**Current behavior :** #1306 
**New behavior :** Working migration from schema V0.7.8 to V0.7.9 for postgres
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1312)
=> fix: flyway postgres migration to V0.7.9

doc/WebApi/swagger.yaml
* Response messages were updated to always return JSON map
* Job loading error returns 400 instead of 500 (500 is still a valid return status code for other cases)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1313)
=> doc(swagger): Update according to last WebAPI changes

project/Dependencies.scala
Currently the build is broken and `sbt update` step doesn't work. This PR should fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1323)
=> fix(build): Change typesafe repository to https

job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala
The ManagerLauncher passes logging options to spark using the
config parameter spark.executor.extraJavaOptions.
This essentially overwrites all other extra java options
configured for the executor in other places (e.g. from the spark
defaults).
Therefore add another environment variable EXECUTOR_EXTRA_SPARK_CONFS
in which you can specify further extra java options that are
appended to the spark.executor.extraJavaOptions (after logging
opts).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1319)
=> feat(launcher): Pass extraJavaOptions to executor

job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala
Within the getJobsByBinaryName there was a call of
zookeeperUtils.list, which was never actually used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1318)
=> fix(zookeeperdao): Remove duplicate list operation

job-server/src/main/scala/spark/jobserver/io/SqlCommon.scala, job-server/src/test/scala/spark/jobserver/io/SqlCommonSpec.scala
Previously only the _limit_ oldest jobs were loaded. If more than
_limit_ jobs were executed, the latest jobs would never be loaded.
Sort jobs in descending start time to always load latest jobs.
**Current behavior :** #1307 
**New behavior :** Jobs are sorted by start time in descending order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1311)
=> fix: sort jobs by start time in descending order

ci/install-python-dependencies.sh, job-server-python/src/python/test/apitests.py, run_tests.sh
* pep8 has been renamed to pycodestyle
New behavior:
pycodestyle is applied for code style guiding
This fixes issue #1320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1327)
=> fix(test): fix Python style guide checker

job-server/src/main/scala/spark/jobserver/io/MetaDataSqlDAO.scala
This change implements the same change as PR https://github.com/spark-jobserver/spark-jobserver/pull/1311, but for the master branch.
`/jobs` endpoint should return jobs in desc order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1325)
=> fix(dao): Jobs endpoint should return jobs in desc order

build.sbt, doc/docker.md, job-server/config/docker.conf
Currently the Jobserver Docker image build is broken. My assumption was that Mesos is not needed in the Docker image, so this change just makes Docker build much more simple and robust by installing pre-compiled Spark with Hadoop only. 
Mesos is removed from the Docker build.
Related issues: https://github.com/spark-jobserver/spark-jobserver/issues/1316, https://github.com/spark-jobserver/spark-jobserver/issues/1259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1324)
=> Fix Docker image

notes/0.10.1.markdown
Release notes for hotfix release `0.10.1` made from the branch `jobserver-0.10.x`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1331)
=> notes(jobserver): Add release notes for 0.10.1

job-server/config/docker.conf, project/plugins.sbt
After the upgrade to Scala 2.12 configuration file for Docker image is incorrect.
Also, version of `sbt-docker` plugin should be bumped because of the following exception:
```
java.lang.RuntimeException: Could not parse image id
```
To run Jobserver with Scala 2.12 in Docker Spark 2.4.2 should be used, because it's the only Spark 2.4.x version, which was compiled with Scala 2.12. 
There is also a compiled version of Spark with Scala 2.12 for other releases, but without Hadoop. Docker image has some dependency issues in this case. Will address this issue in upcoming PRs.
--- …
=> fix(docker): Adapt docker config to updated library versions

build.sbt, ci/install-python-dependencies.sh, doc/python.md, job-server-extras/src/test/scala/spark/jobserver/python/PythonSessionContextFactorySpec.scala, job-server-extras/src/test/scala/spark/jobserver/python/PythonSparkContextFactorySpec.scala, job-server-python/src/python/build.cmd, job-server-python/src/python/build.sh, job-server-python/src/python/run-tests.cmd, job-server-python/src/python/run-tests.sh, job-server-python/src/test/scala/spark/jobserver/python/SubprocessSpec.scala, job-server/src/main/resources/application.conf, notes/0.11.0.markdown, project/PythonTasks.scala
Python 2 has reached EOL last year and should not be used anymore. This commit replaces all references to the "python" binary with the more explicit "python3" binary. If desired, the build can still be performed for Python 2 by settings the "PYTHON_EXECUTABLE" environment variable to an appropriate version .Additionally, python wheels are the preferred way to distribute python code (see https://packaging.python.org/discussions/wheel-vs-egg/). This commit replaces the job-server-python egg with a wheel.
If your `python3` executable points to a python >= 3.8 the `SubprocessSpec` fails as Spark-2.4 [does not support python > 3.7](https://github.com/apache/spark/pull/26194). To resolve this issue set the `PYTHON_EXECUTABLE` to a python version …
=> misc(Python): Replace python 2 with python 3

doc/release.md
1. Added how to publish release for one Scala version (based on experience with release 0.11.0)
2. Updated `release cross` command, which was not working as expected
3. Added a note on releasing hotfixes (based on hotfix release 0.10.1)
4. Added "known issues with test setups" section for some common test exceptions, which block the release process.
Removed the part about announcement of the release as it is seems completely outdated and these steps are not working anymore:
> To announce the release on [ls.implicit.ly](http://ls.implicit.ly/), use [Herald](https://github.com/n8han/herald#install) after adding release notes in
> the `notes/` dir.
--- …
=> Update release documentation

job-server/src/main/scala/spark/jobserver/io/InfoDefinitions.scala
In the previous versions "application/python-archive" was used as MIME type for python binaries. I mistakenly use "python-archive" for backwards compatibility. This commits maps the correct MIME type to Python eggs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1354)
=> bug: backward compatibility of "python-archive"

README.md
As we old releases with the shutdown of Bintray service, maybe it makes sense to update our release information and make it more explicit how to add a resolver now. 
In this commit I also assume that we merge https://github.com/spark-jobserver/spark-jobserver/pull/1364 and make release `0.10.2` available on JFrog as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1365)
=> doc(readme): Update version information and resolver link

README.md
Add release `0.8.1` to the list of releases.
`0.8.x` releases support Spark 2.2 and needed to be republished due to the sunset of Bintray.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1366)
=> doc(readme): Add hotfix release 0.8.1

Dockerfile.test
Currently our Travis CI build is failing due to:
```
gpg: key 99E82A75642AC823: public key "sbt build tool <scalasbt@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.212.90.147 80]
```
This seems to be a common issue connected to the Bintray's sunset.
The most common solution is to use https://repo.scala-sbt.org/scalasbt/debian now.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1377)
=> Fix installation of SBT in Travis CI

.travis.yml, Dockerfile.test, ci/install-python-dependencies.sh
Travis CI build doesn't work anymore, due to a number of reasons:
1. `pip2` can't be installed. `apt-get` is not allowing to install `python-pip` anymore. 
2.  Once `pip2` issue was solved, build started to fail with the following error: 
```
Step 10/14 : RUN sbt update
---> Running in a6a25da779e7 
ls: cannot access '/usr/local/bin/sbt': Operation not permitted 
Could not find launcher jar: /usr/bin/sbt-launch.jar
```
The reason is an underlying Travis CI image, which should be changed to `bionic`.
3. Spark 2.4 can work only with Python versions < 3.8. Currently `apt-get` installs Python 3.9 by default.  Build tools (`wheel` package) now needs to be installed explicitly.
1. Remove installation of `pip2`. SJS was already migrated to use Python 3. …
=> Fix Travis CI build: remove pip2, downgrade python 3, update Travis base image
