README.md
Bintray's maven repository works over https.
=> Get jar via https

akka-app/src/ooyala.common.akka/web/JsonUtils.scala, akka-app/test/ooyala.common.akka/ActorMetricsSpec.scala, akka-app/test/ooyala.common.akka/ActorStackSpec.scala, akka-app/test/ooyala.common.akka/actor/ReaperSpec.scala, akka-app/test/ooyala.common.akka/web/CommonRoutesSpec.scala, akka-app/test/ooyala.common.akka/web/JsonUtilsSpec.scala, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/util/SparkJobUtils.scala, job-server/test/spark.jobserver/JobInfoActorSpec.scala, job-server/test/spark.jobserver/JobManagerSpec.scala, job-server/test/spark.jobserver/JobResultActorSpec.scala, job-server/test/spark.jobserver/JobStatusActorSpec.scala, job-server/test/spark.jobserver/LocalContextSupervisorSpec.scala, job-server/test/spark.jobserver/NamedRddsSpec.scala, job-server/test/spark.jobserver/SparkJobSpec.scala, job-server/test/spark.jobserver/SparkWebUiActorSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala, job-server/test/spark.jobserver/io/JobSqlDAOSpec.scala, job-server/test/spark.jobserver/util/SparkJobUtilsSpec.scala, project/Build.scala, project/Dependencies.scala
This Pull request adds support for spark 1.2.0
It also updates a couple of dependencies
=> Adding support for spark 1.2

job-server/config/local.sh.template
Uncomment YARN_CONF_DIR and replace pathToRemoteConf when running remotely connecting to YARN
=> Update local.sh.template for YARN config

akka-app/src/ooyala.common.akka/metrics/YammerMetrics.scala
BTW maybe it's better to use [metrics-scala](https://github.com/erikvanoosten/metrics-scala) library
=> Timer utility to create Timer metric

project/Dependencies.scala
=> Unable to use yarn-client with spark 1.2.0 #61

bin/server_deploy.sh, bin/server_package.sh
when running the script server-deploy.sh,  there is a error:"job-server/target/spark-job-server.jar: No such file or directory". I had checked the path of spark-job-server.jar is job-server/target/scala-2.10/spark-job-server.jar.
=> the path of spark-job-server.jar is changed when building

README.md
Hi all! 
I work as a software engineer at GumGum and we use spark-jobserver for a forecasting project that use Spark. 
We have been using Spark-Jobserver since November 2014 and we love it! 
I will try to contribute with some code :)
=> update README.md (new company using spark-jobserver)

job-server/src/spark.jobserver/JobManagerActor.scala
Added ExecutionContext backed by fixed thread-pool to JobManagerActor.
Added spark.jobserver.max-dispatcher-per-context (default 2) to reference.conf; for access from both main and test code.
Removed all implicit ExecutionContext references in JobManagerActor, replaced them with explicit once.
=> Added ad-hoc ExecutionContext to dispatch Spark jobs.

bin/server_package.sh
Looks like I had a typo in server_package.sh
=> fix variable name

bin/server_start.sh
=> Fixes #136 - only use executor uri when provided

.gitignore, bin/server_start.sh, job-server/config/local.sh.template
=> Configurable driver memory

README.md, doc/contexts.md, job-server-extras/src/spark.jobserver/StreamingTestJob.scala, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JobServer.scala, job-server/src/spark.jobserver/WebApi.scala, notes/0.5.2.markdown
Two simple fixes:
- Docs from the Streaming change
- Enable environment vars in Typesafe configs
=> A docs fix, and enable env vars in Typesafe configs

job-server/src/spark.jobserver/JobServer.scala
DB connection related exceptions are not caught currently. Catch them,
log and exit while startup.
=> Handle DB connection exceptions, log them and exit

job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/src/test/resources/local.test.jobsqldao.conf
JobSqlDAO to support user and password for security
=> Support username and password in DB access

doc/yarn.md
Documentation to run the jobserver in yarn client mode.
=> Yarn Client Setup

README.md
We're getting a lot of good use out of spark-jobserver, to provide a controlled and standardized access to our spark cluster.  I'd like to add Maana to the list of users.
Thanks!
=> Adding Maana to users list

doc/docker.md
=> Remove SNAPSHOT from Dockerfile definition.

job-server-api/src/spark.jobserver/NamedRddSupport.scala, job-server/src/spark.jobserver/JobServerNamedRdds.scala
Hi, 
we have also just discovered this problem and propose to move the force computation and storage level arguments into the API to let the user decide if the RDD should be precomputed or not.
@velvia: We would appreciate, if this pull request could be merge quickly.
Thanks
The KNIME team
=> Pull request for Issue #247: Allow non-computed named RDDs 

README.md
We have been using the Spark Job Server at Newsweaver for a few months now, so could we add our name to the list of users?
Thanks!
Pierre
=> Adding Newsweaver to list of SJS users

project/Dependencies.scala
Upgrade:
* spray-can -> 1.3.3
* spray-routing -> 1.3.3
* spray-client -> 1.3.3
Spary 1.3.3 contains fixes of different bugs and improvements, here is changelog of Spray 1.3.3
Changelog of Spray 1.3.3: https://github.com/spray/spray/blob/v1.3.3/CHANGELOG
=> Upgrade spray to 1.3.3

doc/chinese/job-server.md
Good thoughts, good architecture, to the Chinese document, better learning
=> the document for  chinese  

README.md
Adding us to the users list - thanks to all contributors.
=> Added Instaclustr to users list

README.md, doc/EMR.md
The following instruction explains how to run spark-jobserver on EMR cluster (Spark on YARN).
=> Add EMR Deploy instruction

job-server/src/main/resources/html/js/spark-jobserver-ui.js
add link to jobid on ui that points to status endpoint
add link after jobid on ui that points to config endpoint
issue #360
=> add links to UI to status and config endpoints for each job. 

README.md
=> Fix small typo in readme.

doc/yarn.md, job-server-extras/src/spark.jobserver/NamedBroadcast.scala, job-server-extras/src/spark.jobserver/NamedObjectsTestJob.scala, job-server-extras/test/spark.jobserver/NamedObjectsJobSpec.scala
I also tested with another set of classes from our repo.  I had a generic test which I wanted to copy/paste in here however I can see that its out of date.  The real test I did does work however it contains company IP and I can't post.
=> Adding NamedBroadcasts with persister

project/Build.scala
build was broken due to a missing file in Build.Scala
=> Fix docker container build

job-server/src/spark.jobserver/JobManagerActor.scala
Logs errors when an exception occur while launching a new job.
Adds a nice message to users in case they try to use the current code with a jar compiled for a previous version.
=> Improving error handling 

README.md, bin/manager_start.sh, job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala
Extract OPTIONAL parameter spark.proxy.user from contextConfig and pa…
=> Support user impersonation for an already Kerberos authenticated user

project/Build.scala, project/plugins.sbt
The title says it all. Please review @velvia and merge at your convenience. Thanks.
=> Upgrade sbt and sbt plugins: sbt-revolver, sbt-assembly, and sbt-docker

README.md
Just updated the from page from reStart to job-server/reStart
=> Change docs so that they work

job-server-extras/test/spark.jobserver/StreamingJobSpec.scala
=> Update test description

job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala
Expression with unit return type，replace map with foreach。
=> replace map with foreach

.travis.yml
=> Add code coverage to .travis.yml

doc/EMR.md, job-server/config/ec2.conf.template, job-server/config/local.conf.template
Remove unused config option `jar-store-rootdir` from sample config files.
=> Fix for issue #509

job-server-extras/test/spark.jobserver/StreamingJobSpec.scala, job-server/src/main/resources/application.conf, job-server/src/spark.jobserver/JobInfoActor.scala, job-server/src/spark.jobserver/io/JobDAO.scala, job-server/src/spark.jobserver/io/JobDAOActor.scala, job-server/src/spark.jobserver/io/JobFileDAO.scala, job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/src/test/resources/local.test.jobsqldao.conf, job-server/src/test/resources/local.test.jobsqldao_dbcp.conf, job-server/test/spark.jobserver/InMemoryDAO.scala, job-server/test/spark.jobserver/JobInfoActorSpec.scala, job-server/test/spark.jobserver/JobManagerSpec.scala, job-server/test/spark.jobserver/io/JobSqlDAOSpec.scala, project/Versions.scala
This upgrades slick to the current latest version, I may be composing this wrong or I may have some style or formatting issues, so please feel free to nit pick a lot on that.
=> Upgrade Slick to 3.1.1

bin/setenv.sh
=> Check Spark directory existence in setenv.sh

job-server/src/spark.jobserver/JobInfoActor.scala, job-server/test/spark.jobserver/JobInfoActorSpec.scala
Fix regression caused by f121807
=> Fix for issue #522

bin/server_start.sh, bin/setenv.sh, job-server/config/local.sh.template
Also, log command output somewhere in case it fails.
=> Make JMX port configurable

job-server/src/spark.jobserver/io/JobSqlDAO.scala, job-server/test/spark.jobserver/io/JobSqlDAOSpec.scala
Can't named a file like test-appName0-2016-08-05T21:12:35.578+08:00.jar in Windows
pull for change it to test-appName0-20160805_092935_568.jar
=> Change saved jar file name for Windows

job-server-extras/test/spark.jobserver/ContextJobSpec.scala, job-server-extras/test/spark.jobserver/HiveJobSpec.scala, job-server-extras/test/spark.jobserver/NamedObjectsJobSpec.scala, job-server-extras/test/spark.jobserver/SqlJobSpec.scala, job-server-extras/test/spark.jobserver/StreamingJobSpec.scala, job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala, job-server/src/spark.jobserver/JobManager.scala, job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/JobServer.scala, job-server/src/spark.jobserver/LocalContextSupervisorActor.scala, job-server/test/spark.jobserver/JobManagerActorSpec.scala, job-server/test/spark.jobserver/JobManagerSpec.scala
Forked JVM processes must have their own JobDAO
=> Partial fix for issue #353

README.md, doc/python.md, job-server-extras/src/spark.jobserver/python/PythonJob.scala, job-server-python/src/python/sparkjobserver/api.py, job-server/config/ec2.conf.template, job-server/config/local.conf.template, job-server/src/spark.jobserver/JobServer.scala
I tried to only make changes which are not objectionable.
=> Fix typos, grammar, whitespace

job-server/config/local.conf.template, job-server/src/spark.jobserver/DataManagerActor.scala, job-server/src/spark.jobserver/io/DataFileDAO.scala
Also, standardize rootdirs and add missing datadao config
to local.conf.template.
=> Return error if data file can't be deleted

job-server/src/spark.jobserver/JobManagerActor.scala, job-server/src/spark.jobserver/JobStatusActor.scala, job-server/src/spark.jobserver/WebApi.scala, job-server/test/spark.jobserver/WebApiMainRoutesSpec.scala, job-server/test/spark.jobserver/WebApiSpec.scala
Merged PR #541 because of inactivity.
Of course all honour to @leoromanovsky
=> Issue #536: Web API returns status "KILLED" for jobs cancelled by user.

project/plugins.sbt
This can be added to ~/.sbt/0.13/plugins/plugins.sbt
=> Remove user specific ensime plugin

project/Dependencies.scala
=> Fix issue #699: Use spray-routing-shapeless23

README.md
Additional instructions for running H2 in server-mode
=> H2 in server-mode

build.sbt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/784)
=> Add Maven 3.3.9 to docker

doc/docker.md, doc/yarn.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/790)
=> update documentation with docker image 0.7.0

notes/0.7.0.markdown
* Add Synchronous delete change to 0.7.0 release notes.
=> doc(notes): Synchronous delete change missing

README.md, doc/mesos.md
With reference to issue #812, adding mesos mode configuration steps. The steps mentioned in the configuration worked for me.
@LeightonWong you might also want to review the steps once.
=> Mesos config tips

README.md, doc/mesos.md
(cherry picked from commit 7e481cc)
Committing the same changes as #832 in master.
=> docs: Mesos config tips

Dockerfile.test, ci/install-spark.sh, job-server-extras/src/test/scala/spark/jobserver/python/PythonSparkContextFactorySpec.scala, job-server-python/src/python/run-tests.sh, job-server-python/src/test/scala/spark/jobserver/python/SubprocessSpec.scala, project/Versions.scala
=> fix(ci): Use spark version 2.1.0 in ci tests

job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala
Pull Request checklist
Current behavior : big written file couldn't be read back. 
New behavior : read back is correct.
=> fix(cassandra): fix deseriazilation issue of cassandra repository

doc/javaapi.md
None:
Added some docs for Java API
=> Added documentation for the Java API.

akka-app/src/main/scala/spark/jobserver/common/akka/web/CommonRoutes.scala, akka-app/src/main/scala/spark/jobserver/common/akka/web/JsonUtils.scala, job-server-api/src/main/scala/spark/jobserver/NamedRddSupport.scala, job-server-api/src/main/scala/spark/jobserver/SparkJob.scala, job-server-api/src/main/scala/spark/jobserver/context/SparkContextFactory.scala, job-server-api/src/main/scala/spark/jobserver/util/SparkJobUtils.scala, job-server-extras/src/main/scala/spark/jobserver/NamedObjectsTestJob.scala, job-server-extras/src/main/scala/spark/jobserver/context/HiveContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/context/SQLContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/context/StreamingContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/python/PythonContextFactory.scala, job-server-extras/src/main/scala/spark/jobserver/python/PythonJob.scala, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/BinaryManager.scala, job-server/src/main/scala/spark/jobserver/CorsSupport.scala, job-server/src/main/scala/spark/jobserver/JobInfoActor.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/JobServerNamedObjects.scala, job-server/src/main/scala/spark/jobserver/JobServerSprayProtocol.scala, job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/auth/SJSAuthenticator.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/io/JobFileDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/util/LRUCache.scala, scalastyle-config.xml
There several small checks that we can add to scalastyle to improve readability
and to make the code base consistent. One of them is space checks before and
after tokens.
There are no style checks for space before and after certain tokens like if, :, , etc.
Add checks for space and before tokens.
Nothing
=> fix(misc): Add space checkers in scalastyle

README.md, job-server/src/main/scala/spark/jobserver/WebApi.scala
=> feat(api): Add support for HTTP override

Dockerfile.test, README.md, ci/install-spark.sh, job-server-python/src/python/test/apitests.py, project/Dependencies.scala, project/Versions.scala
We are using spark 2.1.0
Use latest version 2.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/845)
=> fix(core): Update spark version to 2.2.0

.github/issue_template.md
In most of the issues, the first question is ,,what spark and jobserver version are you using?''. Hopefully this template eliminates this questions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/935)
=> misc(github): add issue template

README.md
Missing README.md entry
Update README.md with Branchmetrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/955)
=> Add Branch to README.md

job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala
- If the binary is already available in the
binaries_contents then the select query will load
all the binary content because we have a select *
statement. A map(_.binId) is added to do specific
select
- Since output of first insert statement is not used
anywhere, there is no need to get the binId back. This
avoids the following queries
SELECT SCOPE_IDENTITY() WHERE SCOPE_IDENTITY() IS NOT NULL;
- Remove extra map(bc => bc.*) to simplify the code
Change-Id: I7f8c1372bf8db22dac999a641e9e965f3f0adea0
If user is uploading small jar files a few extra queries and pulling the whole jar file back is not a big …
=> fix(jobserver): Simplify and optimize query

job-server-extras/src/main/scala/spark/jobserver/python/PythonJob.scala, job-server-python/src/python/sparkjobserver/subprocess.py
- [x ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
**Current behavior:** https://github.com/spark-jobserver/spark-jobserver/issues/940
**New behavior:** Support  Adding application egg to Pyspark context
Didn't want to hardcode path version of examples egg, so did not include new unit test, will add if someone has a convention for adding a reference to the generated egg.  all of the existing tests do not make use of any egg files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/941)
=> Support Adding Application Egg to PySpark

doc/python.md
- [x ] The commit(s) message(s) follows the contribution [guidelines](doc/contribution-guidelines.md#commit-message-format) ?
- [ x] Docs have been added / updated (for bug fixes / features) ?
Updated Python Documentation to remove depreciated interfaces and updated to use new PythonSessionContextFactory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/984)
=> Updated Python documentation to reference PythonSession

job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala
In an earlier change [1] a new route for getting context info was
added. Due to the fact that the necessary case class GetSparkWebUI is
only implemented in class LocalContextSupervisorActor and is
missing in class AkkaClusterSupervisorActor, this patch only works for
the standalone version of Spark Job Server.
This patch provides the necessary implementation of GetSparkWebUI in
class AkkaClusterSupervisorActor and enables this feature
also if "context-per-jvm" is set to true.
[1] PR: #869 feat(webapi): add route for getting context info
#1007 
See commit message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobse …
=> fix(webapi): repair context info route for mode context-per-jvm

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1025)
=> Improved documentation in readme for H2 db

akka-app/README.md, doc/EC2.md, doc/EMR.md, doc/actors.md, doc/chinese/job-server.md, doc/cluster.md, doc/contexts.md, doc/contribution-guidelines.md, doc/docker.md, doc/jmx.md, doc/job-server-flow.md, doc/logging.md, doc/mesos.md, doc/python.md, doc/troubleshooting.md, doc/yarn.md
N/A
N/A
N/A
This pull request is only an update to the docs. It adds a new doc in `/doc` called `logging.md` that details logging configurations of Client vs Cluster Mode. It also adds a note to `cluster.md` clarifying an assumption that wasn't so obvious to me.
--- …
=> docs(jobserver): Add new logging doc and a line to cluster doc

doc/jmx.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1054)
=> docs(jobserver): Update JMX documentation for Akka Cluster

notes/0.8.1.markdown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1081)
=> Updated notes with all changes since Launcher

job-server/src/main/resources/html/js/spark-jobserver-ui.js
change contextDetail.context to contextDetail.name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1113)
=> fix(ui):fix context detail in ui

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobDAOActor.scala, job-server/src/main/scala/spark/jobserver/util/CustomException.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobServerSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobDAOActorSpec.scala, scalastyle-config.xml
All commits have relevant information in the commit message. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1126)
=> Multiple fixes for jobserver

job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobServer.scala, job-server/src/main/scala/spark/jobserver/io/FileCacher.scala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1141)
=> Remove temp folders & handle timeout exception

build.sbt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1158)
=> misc(jobserver): Used correct spark URL in build.sbt (#1155)

build.sbt, ci/install-spark.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1171)
=> misc(jobserver): Used correct spark download URL

akka-app/src/main/scala/spark/jobserver/common/akka/ActorMetrics.scala, akka-app/src/main/scala/spark/jobserver/common/akka/metrics/YammerMetrics.scala, job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala, job-server/src/main/scala/spark/jobserver/io/FileCacher.scala, job-server/src/main/scala/spark/jobserver/io/HdfsBinaryDAO.scala, job-server/src/main/scala/spark/jobserver/io/JobSqlDAO.scala, job-server/src/main/scala/spark/jobserver/io/MetaDataSqlDAO.scala, job-server/src/main/scala/spark/jobserver/io/SqlCommon.scala, job-server/src/main/scala/spark/jobserver/util/HadoopFSFacade.scala, job-server/src/main/scala/spark/jobserver/util/Utils.scala, job-server/src/test/resources/local.test.metadatasqldao.conf, job-server/src/test/scala/spark/jobserver/io/CombinedDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/HdfsBinaryDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/MetaDataSqlDAOSpec.scala, job-server/src/test/scala/spark/jobserver/util/HadoopFSFacadeSpec.scala
The PR consists of 6 commits and each commit has its own description explaining what the fix is doing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1172)
=> Improvements and fixes for combined dao

job-server/src/test/scala/spark/jobserver/JobManagerSpec.scala, job-server/src/test/scala/spark/jobserver/io/HdfsBinaryDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/SqlCommonSpec.scala, job-server/src/test/scala/spark/jobserver/util/HDFSCluster.scala, job-server/src/test/scala/spark/jobserver/util/HadoopFSFacadeSpec.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala
Remove concurrency for save operations in tests, use random HDFS port for HDFS tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1179)
=> Small fixes for tests

build.sbt, job-server/config/log4j-cluster.properties, job-server/config/log4j-server.properties, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/io/InfoDefinitions.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala, job-server/src/main/scala/spark/jobserver/util/JsonProtocols.scala, job-server/src/test/scala/spark/jobserver/io/CombinedDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/zookeeper/ZookeeperUtilsSpec.scala, job-server/src/test/scala/spark/jobserver/util/CuratorTestCluster.scala, job-server/src/test/scala/spark/jobserver/util/JsonProtocolsSpec.scala, project/Dependencies.scala, project/ExclusionRules.scala, project/Versions.scala
Going forward with the [sets of changes proposed in #1148](https://github.com/spark-jobserver/spark-jobserver/issues/1148) this PR continues the work of [#1169](https://github.com/spark-jobserver/spark-jobserver/pull/1169) and adds Zookeeper as one implementation for a metadata DAO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1191)
=> Add Zookeeper DAO for metadata

README.md, doc/cluster.md, doc/dao-setup.md, doc/job-server-flow.md, doc/mesos.md, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala
- Added documentation for new CombinedDAO.
- Fixing Zookeeper timeouts issue (due to incorrect timeout settings, when one of Zookeepers was not available ConnectionLoss exception was raised). Client will try to open connection to another Zookeeper instance if first chosen is not available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1201)
=> CombinedDAO: Fix Zookeeper timeouts and add documentation

job-server/src/main/scala/spark/jobserver/WebApi.scala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1200)
=> Minor refactor for WebApi logging

job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala
Recently introduced changes contain a metadata DAO for zookeeper, which is an eventually consistent, highly available database (latter one being the main point to go with zookeeper).
Since we actually want to maintain the consistency of the synchronous API, that we got from the  
current SQL DAOs, this change introduces an active sync call before every read operation, that ensures that every completed write transaction so far is reflected upon the following read. 
This basically makes Zookeeper a consistent system in our context.
**Details**
* Add sync operation to ZookeeperUtils
* Add sync call to every MetaDataZookeperDAO read operation
The asynchronous sync call will ensure that the next read call
contains all the …
=> feat(jobserver): Force consistent read with manual sync

job-server/src/main/scala/spark/jobserver/JobManagerActor.scala
Acted on one of old TODO notes in Jobserver code :)
Commit removes blocking Await call from job creation in JobManagerActor.
Passing now also a sender to startJobInternal function, otherwise
we will see wrong sender in Future thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1207)
=> Remove blocking await from StartJob

job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobStatusActor.scala, job-server/src/main/scala/spark/jobserver/io/JobDAO.scala, job-server/src/test/scala/spark/jobserver/io/CombinedDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobCassandraDAOSpec.scala
Details can be found within each commit.
Note: If change is ready for merging then rebase and merge option should be used. 
Minor fixes and improved logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1214)
=> Minor fixes and improved logging

doc/job-server-flow.md
Created this sequence diagram while analyzing context creation flow and thought that it was worth contributing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1215)
=> doc(jobserver): Add context creation flow diagram

job-server/src/main/scala/spark/jobserver/WebApi.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/ZookeeperUtils.scala, job-server/src/main/scala/spark/jobserver/util/Utils.scala
This PR adds metrics to WebAPI and ZookeeperDAO to get more insight into jobserver performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1218)
=> Timers for WebAPI and Zookeeper

job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobWithNamedRddsSpec.scala, job-server/src/test/scala/spark/jobserver/io/JobSqlDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/MetaDataSqlDAOSpec.scala, job-server/src/test/scala/spark/jobserver/io/SqlCommonSpec.scala, job-server/src/test/scala/spark/jobserver/io/SqlTestHelpers.scala
Tests of Jobserver are a bit flaky sometimes. I tried to debug some of them a bit and as a result, made a bit of refactoring and a couple of improvements to the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1225)
=> Fixes and refactoring for tests

job-server/src/main/scala/spark/jobserver/JobManager.scala, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala
Some minor log improvements that resulted from refactorings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1228)
=> Log improvements

doc/job-server-flow.md, job-server/src/main/scala/spark/jobserver/JobManagerActor.scala, job-server/src/main/scala/spark/jobserver/JobStatusActor.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
See commit messages for more details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1233)
=> Only respond if cleanup is complete

README.md, job-server/src/main/scala/akka/downing/KeepOldestDowningProvider.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala, job-server/src/test/scala/spark/jobserver/JobSpecBase.scala
**Change summary**:
Tests have been very flaky in the past and a lot of unrelated tests fail for the open pull requests.
Fix these flaky tests (mostly JobManagerActorSpec and AkkaClusterSupervisorSpec) and also do some minor refactoring and related documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1262)
=> Test improvements

job-server/src/main/scala/spark/jobserver/io/CombinedDAO.scala, job-server/src/main/scala/spark/jobserver/io/zookeeper/MetaDataZookeeperDAO.scala
**Changes:**
* Move existing timers from MetaDataZookeeperDAO to CombinedDAO so that we get a full picture of the performance of both binary and metadata DAO and other DAO implementations can  leverage this measurement.
* Also do a little bit of refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1258)
=> Move timer metrics to CombinedDAO

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1270)
=> doc(readme): Update outdated coverage test command

README.md, job-server/src/main/scala/spark/jobserver/io/JobCassandraDAO.scala
https://github.com/spark-jobserver/spark-jobserver/issues/1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1272)
=> refactor(cassandra): Deprecate Cassandra DAO

bin/server_start.sh, bin/setenv.sh, job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala, job-server/src/test/scala/spark/jobserver/util/ManagerLauncherSpec.scala
- Print whole date in gc logs instead of just relative time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1292)
=> Add date to gc logs

doc/jmx.md
The command can be very useful in some cases, so I thought it would be good to add it to jmx documentation in Jobserver to avoid long search in Google in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1295)
=> doc(jmx): Add example how to down a node from jmx-cli

job-server/src/test/scala/spark/jobserver/InMemoryDAO.scala
Change-Id: Ib72fe7b29468dbf70a3f9d266f08ba1f25cff2ed
InMemory dao is using JobDAO which is supposed to removed in future.
Adapt InMemory dao to use binary/meta dao interfaces so it becomes easier to JobDAO in future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1296 …
=> feat(test): Convert in-memory dao to combineddao

job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala
Last weeks master branch and all open PRs are failing on some of `AkkaClusterSupervisorActorSpec` tests:
- The failure is very hard to reproduce locally (out of 30 runs, I had only 2 failures of 2 different tests). 
- There are no recent changes to this part of the code + I found some instances of this test failure in history of Jenkins.
From the code and exception analysis it seems that there is a small timing issue. All failing tests create new context, then take context information from DAO and then ask for the same
information from `AkkaClusterSupervisorActor`.
If creation of the context is slow enough then pulling data from DAO will return context in `STARTED` stated. `RUNNING` state is assigned later than the confirmation of the context creation sent.
Using simple retry waiting for …
=> Fix failing AkkaClusterSupervisorActorSpec tests

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1301)
=> doc(readme): Update supported Spark versions table

job-server/src/main/scala/spark/jobserver/WebApi.scala
Add counter for WebAPI responding with internal server error (status code 500).
This counter should help to detect situations, when Jobserver is up and running, but some of the components have problems and requests are not correctly processed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1308)
=> feat(webpi): Add counter for internal server error

README.md, build.sbt, doc/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1314)
=> Extend release process documentation

README.md
* Cadenz.ai uses Spark Jobserver as a REST service for Spark to handle low latency OLAP queries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1322)
=> docs(README): Add Cadenz.ai to the users list

project/Dependencies.scala
Tests for the branch `jobserver-0.10.x` are failing and https://github.com/spark-jobserver/spark-jobserver/pull/1329 can't be merged.
Apply the patch from the `master` branch for the Typesafe repository to the `jobserver-0.10.x` branch as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1330)
=> fix(build): Change typesafe repository to https

job-server/src/main/scala/db/postgresql/migration/V0_7_3/V0_7_3__Migrate_Blobs.scala, job-server/src/main/scala/db/postgresql/migration/V0_7_5/V0_7_5__Migrate_Blobs.scala, job-server/src/main/scala/db/postgresql/migration/V0_7_9/V0_7_9__jobinfo_contains_uris.scala
**Current behavior :** Previously, exceptions during postgres migration where only logged but did not abort migration. For example, if the postgres extension lo is not present, V0.7.3 and V0.7.5 log an exception but are recorded as successful. V0.7.6 finally fails, as an expected table is not present. As a result, the migration will always continue from V0.7.6 but never succeed, even when the extension was manually added.
**New behavior :** The flyway migration will correctly record a migration step as failed if an exception is raised. Subsequent migrations will continue from the failed step.
I think the changes are only relevant for the jobserver-0.10.x branch and not for master. But if the changes are also relevant for master I can provide an additional PR. …
=> fix: Fail postgres migration on exception

job-server/src/main/scala/spark/jobserver/WebApi.scala
**Current behavior :** Previously, context resets blocked the thread to wait for the result. Additionally, if any context could not be stopped, the request is still reported as handled successfully.
**New behavior :** Do not block during context shutdown. Check if all contexts have been shutdown successfully, otherwise return InternalServerError.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1350)
=> refactor(Context Reset): Make context resets async and report exceptions

job-server/src/test/scala/spark/jobserver/JobManagerActorSpec.scala
**Current behavior :** Partial solution for #1363
**New behavior :** Add fallback for async job results. If job results are not present yet, sleep for a few seconds and try loading again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1367)
=> test: Improve stability of async jobs tests

doc/actors.md, doc/job-server-flow.md, doc/start-job-msg-flow-AdHocJobManagerActor.md, doc/success-job-flow.md, doc/troubleshooting.md, job-server/src/main/resources/application.conf, job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala, job-server/src/main/scala/spark/jobserver/LocalContextSupervisorActor.scala, job-server/src/test/scala/spark/jobserver/AkkaClusterSupervisorActorSpec.scala, job-server/src/test/scala/spark/jobserver/JavaJobSpec.scala, job-server/src/test/scala/spark/jobserver/JobSpecBase.scala, job-server/src/test/scala/spark/jobserver/LocalContextSupervisorSpec.scala
This PR updates documentation after the changes made in https://github.com/spark-jobserver/spark-jobserver/pull/1375:
- Remove all mentions of `JobResult` actor
- Update diagrams accordingly
- Remove unused variables from the config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1381)
=> Update documentation after removal of JobResultActor

README.md
Updating Cadenz.AI to Lentra - Cadenz
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spark-jobserver/spark-jobserver/1404)
=> Lentra Acquired TheDatateam
